CREATE TABLE T_DISCOVERY (
  ID     BIGINT NOT NULL AUTO_INCREMENT,
  DICE INTEGER,
  LAND   BIT,
  CHECKLEADER   BIT,
  CHECKLEADERNOTROOPS   BIT,
  RESULT VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE T_ATTRITION_OTHER (
  ID     BIGINT NOT NULL AUTO_INCREMENT,
  DICE INTEGER,
  LOSSPERCENTAGE   INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE T_ATTRITION_LAND_EUROPE (
  ID     BIGINT NOT NULL AUTO_INCREMENT,
  DICE INTEGER,
  MINSIZE   INTEGER,
  MAXSIZE   INTEGER,
  LOSS   INTEGER,
  PILLAGE   BIT,
  PRIMARY KEY (ID)
);