CREATE TABLE ATTRITION (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ID_GAME BIGINT,
  TURN INTEGER,
  TYPE VARCHAR(255),
  STATUS VARCHAR(255),
  SIZE DOUBLE,
  TECH VARCHAR(255),
  BONUS INTEGER,
  DIE INTEGER,
  R_PROVINCES VARCHAR(255),
  PRIMARY KEY (ID)
);

ALTER TABLE ATTRITION
ADD INDEX FK_ATTRITION_GAME (ID_GAME),
ADD CONSTRAINT FK_ATTRITION_GAME
FOREIGN KEY (ID_GAME)
REFERENCES GAME (ID);

CREATE TABLE ATTRITION_COUNTER (
  ID_ATTRITION         BIGINT NOT NULL,
  ID_COUNTER  BIGINT NOT NULL,
  COUNTRY VARCHAR(255),
  `TYPE` VARCHAR(255),
  CODE VARCHAR(255),
  PRIMARY KEY (ID_ATTRITION, ID_COUNTER)
);

ALTER TABLE ATTRITION_COUNTER
ADD INDEX ATTRITION_COUNTER_ATTRITION (ID_ATTRITION),
ADD CONSTRAINT ATTRITION_COUNTER_ATTRITION
FOREIGN KEY (ID_ATTRITION)
REFERENCES ATTRITION (ID);

CREATE TABLE ATTRITION_PROVINCE (
  ID_ATTRITION         BIGINT NOT NULL,
  R_PROVINCE  VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID_ATTRITION, PROVINCE)
);

ALTER TABLE ATTRITION_PROVINCE
ADD INDEX ATTRITION_PROVINCE_ATTRITION (ID_ATTRITION),
ADD CONSTRAINT ATTRITION_PROVINCE_ATTRITION
FOREIGN KEY (ID_ATTRITION)
REFERENCES ATTRITION (ID);
