DELETE FROM T_MNU;

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (1, 'angleterre', 'MNU_ART_MINUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (2, 'angleterre', 'MNU_ART_PLUS', 24);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (3, 'angleterre', 'MNU_WOOD_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (4, 'angleterre', 'MNU_WOOD_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (5, 'angleterre', 'MNU_CEREALS_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (6, 'angleterre', 'MNU_CEREALS_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (7, 'angleterre', 'MNU_INSTRUMENTS_MINUS', 9);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (8, 'angleterre', 'MNU_INSTRUMENTS_PLUS', 18);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (9, 'angleterre', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (10, 'angleterre', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (11, 'angleterre', 'MNU_FISH_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (12, 'angleterre', 'MNU_FISH_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (13, 'angleterre', 'MNU_CLOTHES_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (14, 'angleterre', 'MNU_CLOTHES_PLUS', 12);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (15, 'espagne', 'MNU_ART_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (16, 'espagne', 'MNU_ART_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (17, 'espagne', 'MNU_INSTRUMENTS_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (18, 'espagne', 'MNU_INSTRUMENTS_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (19, 'espagne', 'MNU_METAL_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (20, 'espagne', 'MNU_METAL_PLUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (21, 'espagne', 'MNU_FISH_MINUS', 3);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (22, 'espagne', 'MNU_FISH_PLUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (23, 'espagne', 'MNU_CLOTHES_MINUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (24, 'espagne', 'MNU_CLOTHES_PLUS', 16);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (25, 'espagne', 'MNU_SALT_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (26, 'espagne', 'MNU_SALT_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (27, 'espagne', 'MNU_WINE_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (28, 'espagne', 'MNU_WINE_PLUS', 8);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (29, 'france', 'MNU_ART_MINUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (30, 'france', 'MNU_ART_PLUS', 24);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (31, 'france', 'MNU_WOOD_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (32, 'france', 'MNU_WOOD_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (33, 'france', 'MNU_CEREALS_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (34, 'france', 'MNU_CEREALS_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (35, 'france', 'MNU_INSTRUMENTS_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (36, 'france', 'MNU_INSTRUMENTS_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (37, 'france', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (38, 'france', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (39, 'france', 'MNU_FISH_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (40, 'france', 'MNU_FISH_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (41, 'france', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (42, 'france', 'MNU_CLOTHES_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (43, 'france', 'MNU_SALT_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (44, 'france', 'MNU_SALT_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (45, 'france', 'MNU_WINE_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (46, 'france', 'MNU_WINE_PLUS', 8);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (47, 'habsbourg', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (48, 'habsbourg', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (49, 'habsbourg', 'MNU_CEREALS_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (50, 'habsbourg', 'MNU_CEREALS_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (51, 'habsbourg', 'MNU_INSTRUMENTS_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (52, 'habsbourg', 'MNU_INSTRUMENTS_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (53, 'habsbourg', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (54, 'habsbourg', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (55, 'habsbourg', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (56, 'habsbourg', 'MNU_CLOTHES_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (57, 'habsbourg', 'MNU_SALT_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (58, 'habsbourg', 'MNU_SALT_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (59, 'hollande', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (60, 'hollande', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (61, 'hollande', 'MNU_INSTRUMENTS_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (62, 'hollande', 'MNU_INSTRUMENTS_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (63, 'hollande', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (64, 'hollande', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (65, 'hollande', 'MNU_FISH_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (66, 'hollande', 'MNU_FISH_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (67, 'hollande', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (68, 'hollande', 'MNU_CLOTHES_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (69, 'pologne', 'MNU_ART_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (70, 'pologne', 'MNU_ART_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (71, 'pologne', 'MNU_WOOD_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (72, 'pologne', 'MNU_WOOD_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (73, 'pologne', 'MNU_CEREALS_MINUS', 3);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (74, 'pologne', 'MNU_CEREALS_PLUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (75, 'pologne', 'MNU_INSTRUMENTS_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (76, 'pologne', 'MNU_INSTRUMENTS_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (77, 'pologne', 'MNU_METAL_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (78, 'pologne', 'MNU_METAL_PLUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (79, 'pologne', 'MNU_SALT_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (80, 'pologne', 'MNU_SALT_PLUS', 8);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (81, 'portugal', 'MNU_ART_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (82, 'portugal', 'MNU_ART_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (83, 'portugal', 'MNU_INSTRUMENTS_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (84, 'portugal', 'MNU_INSTRUMENTS_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (85, 'portugal', 'MNU_METAL_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (86, 'portugal', 'MNU_METAL_PLUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (87, 'portugal', 'MNU_FISH_MINUS', 3);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (88, 'portugal', 'MNU_FISH_PLUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (89, 'portugal', 'MNU_SALT_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (90, 'portugal', 'MNU_SALT_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (91, 'portugal', 'MNU_WINE_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (92, 'portugal', 'MNU_WINE_PLUS', 8);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (93, 'prusse', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (94, 'prusse', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (95, 'prusse', 'MNU_WOOD_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (96, 'prusse', 'MNU_WOOD_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (97, 'prusse', 'MNU_INSTRUMENTS_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (98, 'prusse', 'MNU_INSTRUMENTS_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (99, 'prusse', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (100, 'prusse', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (101, 'prusse', 'MNU_METAL_SCHLESIEN_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (102, 'prusse', 'MNU_METAL_SCHLESIEN_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (103, 'prusse', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (104, 'prusse', 'MNU_CLOTHES_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (105, 'russie', 'MNU_ART_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (106, 'russie', 'MNU_ART_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (107, 'russie', 'MNU_WOOD_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (108, 'russie', 'MNU_WOOD_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (109, 'russie', 'MNU_CEREALS_MINUS', 3);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (110, 'russie', 'MNU_CEREALS_PLUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (111, 'russie', 'MNU_INSTRUMENTS_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (112, 'russie', 'MNU_INSTRUMENTS_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (113, 'russie', 'MNU_METAL_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (114, 'russie', 'MNU_METAL_PLUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (115, 'russie', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (116, 'russie', 'MNU_CLOTHES_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (117, 'suede', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (118, 'suede', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (119, 'suede', 'MNU_WOOD_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (120, 'suede', 'MNU_WOOD_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (121, 'suede', 'MNU_INSTRUMENTS_MINUS', 9);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (122, 'suede', 'MNU_INSTRUMENTS_PLUS', 18);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (123, 'suede', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (124, 'suede', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (125, 'suede', 'MNU_FISH_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (126, 'suede', 'MNU_FISH_PLUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (127, 'suede', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (128, 'suede', 'MNU_CLOTHES_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (129, 'turquie', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (130, 'turquie', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (131, 'turquie', 'MNU_WOOD_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (132, 'turquie', 'MNU_WOOD_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (133, 'turquie', 'MNU_CEREALS_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (134, 'turquie', 'MNU_CEREALS_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (135, 'turquie', 'MNU_INSTRUMENTS_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (136, 'turquie', 'MNU_INSTRUMENTS_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (137, 'turquie', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (138, 'turquie', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (139, 'turquie', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (140, 'turquie', 'MNU_CLOTHES_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (141, 'turquie', 'MNU_SALT_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (142, 'turquie', 'MNU_SALT_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (143, 'venise', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (144, 'venise', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (145, 'venise', 'MNU_INSTRUMENTS_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (146, 'venise', 'MNU_INSTRUMENTS_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (147, 'venise', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (148, 'venise', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (149, 'venise', 'MNU_SALT_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (150, 'venise', 'MNU_SALT_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (151, 'venise', 'MNU_WINE_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (152, 'venise', 'MNU_WINE_PLUS', 8);