CREATE TABLE T_PERIOD (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  NAME    VARCHAR(255),
  BEGIN    INTEGER,
  END    INTEGER,
  PRIMARY KEY (ID)
);

INSERT INTO T_PERIOD (ID, NAME, BEGIN, END)
VALUES (1, 'I', 1, 6);
INSERT INTO T_PERIOD (ID, NAME, BEGIN, END)
VALUES (2, 'II', 7, 14);
INSERT INTO T_PERIOD (ID, NAME, BEGIN, END)
VALUES (3, 'III', 15, 25);
INSERT INTO T_PERIOD (ID, NAME, BEGIN, END)
VALUES (4, 'IV', 26, 34);
INSERT INTO T_PERIOD (ID, NAME, BEGIN, END)
VALUES (5, 'V', 35, 42);
INSERT INTO T_PERIOD (ID, NAME, BEGIN, END)
VALUES (6, 'VI', 43, 52);
INSERT INTO T_PERIOD (ID, NAME, BEGIN, END)
VALUES (7, 'VII', 53, 62);

CREATE TABLE T_TECH (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  NAME    VARCHAR(255),
  LAND    BIT,
  R_COUNTRY    VARCHAR(255),
  BEGIN_BOX   INTEGER,
  BEGIN_TURN  INTEGER,
  PRIMARY KEY (ID)
);

INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (1, 'MEDIEVAL', true, null, 0, 0);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (2, 'RENAISSANCE', true, null, 10, 1);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (3, 'TERCIO', true, 'espagne', 16, 6);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (4, 'ARQUEBUS', true, null, 21, 11);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (5, 'MUSKET', true, null, 30, 21);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (6, 'BAROQUE', true, null, 40, 33);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (7, 'MANOEUVRE', true, null, 51, 40);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (8, 'LACE_WAR', true, null, 67, 57);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (9, 'CARRACK', false, null, 0, 0);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (10, 'NAE_GALEON', false, null, 11, 7);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (11, 'GALLEON_FLUYT', false, null, 24, 15);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (12, 'GALLEASS', false, 'venise', 28, 17);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (13, 'BATTERY', false, null, 34, 21);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (14, 'VESSEL', false, null, 44, 32);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (15, 'THREE_DECKER', false, null, 58, 41);
INSERT INTO T_TECH (ID, NAME, LAND, R_COUNTRY, BEGIN_BOX, BEGIN_TURN)
VALUES (16, 'SEVENTY_FOUR', false, null, 68, 50);

CREATE TABLE T_BASIC_FORCE (
  ID           BIGINT NOT NULL AUTO_INCREMENT,
  R_COUNTRY VARCHAR(255),
  ID_PERIOD   BIGINT,
  NUMBER       INTEGER,
  TYPE         VARCHAR(255),
  PRIMARY KEY (ID)
);

ALTER TABLE T_BASIC_FORCE
ADD INDEX FK_T_BASIC_FORCE_T_PERIOD (ID_PERIOD),
ADD CONSTRAINT FK_T_BASIC_FORCE_T_PERIOD
FOREIGN KEY (ID_PERIOD)
REFERENCES T_PERIOD (ID);

CREATE TABLE T_UNIT (
  ID           BIGINT NOT NULL AUTO_INCREMENT,
  R_COUNTRY VARCHAR(255),
  ID_TECH   BIGINT,
  PRICE       INTEGER,
  TYPE         VARCHAR(255),
  ACTION    VARCHAR(255),
  SPECIAL   BIT,
  PRIMARY KEY (ID)
);

ALTER TABLE T_UNIT
ADD INDEX FK_T_UNIT_T_TECH (ID_TECH),
ADD CONSTRAINT FK_T_UNIT_T_TECH
FOREIGN KEY (ID_TECH)
REFERENCES T_TECH (ID);