ALTER TABLE SIEGE
ADD COLUMN STATUS VARCHAR(255);

CREATE TABLE SIEGE_COUNTER (
  ID_SIEGE         BIGINT NOT NULL,
  ID_COUNTER  BIGINT NOT NULL,
  PRIMARY KEY (ID_SIEGE, ID_COUNTER)
);

ALTER TABLE SIEGE_COUNTER
ADD INDEX SIEGE_COUNTER_SIEGE (ID_SIEGE),
ADD CONSTRAINT SIEGE_COUNTER_SIEGE
FOREIGN KEY (ID_SIEGE)
REFERENCES SIEGE (ID);

ALTER TABLE SIEGE_COUNTER
ADD INDEX SIEGE_COUNTER_COUNTER (ID_COUNTER),
ADD CONSTRAINT SIEGE_COUNTER_COUNTER
FOREIGN KEY (ID_COUNTER)
REFERENCES COUNTER (ID);