CREATE TABLE T_LIMIT (
  ID           BIGINT NOT NULL AUTO_INCREMENT,
  R_COUNTRY VARCHAR(255),
  ID_PERIOD   BIGINT,
  NUMBER       INTEGER,
  TYPE         VARCHAR(255),
  PRIMARY KEY (ID)
);

ALTER TABLE T_LIMIT
ADD INDEX FK_T_LIMIT_T_PERIOD (ID_PERIOD),
ADD CONSTRAINT FK_T_LIMIT_T_PERIOD
FOREIGN KEY (ID_PERIOD)
REFERENCES T_PERIOD (ID);