ALTER TABLE R_PROVINCE_EU
ADD COLUMN FORTRESS INTEGER;

ALTER TABLE R_PROVINCE_EU
ADD COLUMN CAPITAL BIT;

ALTER TABLE R_PROVINCE_EU
ADD COLUMN ARSENAL BIT;

ALTER TABLE R_PROVINCE_EU
ADD COLUMN METADATA VARCHAR(255);

