ALTER TABLE GAME
  ADD COLUMN VERSION BIGINT NOT NULL;

CREATE TABLE D_DIFF (
  ID     BIGINT NOT NULL AUTO_INCREMENT,
  TYPE VARCHAR(255),
  TYPE_OBJECT VARCHAR(255),
  ID_OBJECT   BIGINT,
  ID_GAME   BIGINT,
  VERSION_GAME   BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE D_ATTRIBUTE (
  ID     BIGINT NOT NULL AUTO_INCREMENT,
  TYPE VARCHAR(255),
  VALUE VARCHAR(255),
  ID_DIFF   BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE D_ATTRIBUTE
ADD INDEX FK_D_ATTRIBUTE_D_DIFF (ID_DIFF),
ADD CONSTRAINT FK_D_ATTRIBUTE_D_DIFF
FOREIGN KEY (ID_DIFF)
REFERENCES D_DIFF (ID);