ALTER TABLE COLONY
DROP INDEX FK_COLONY_COUNTER,
DROP FOREIGN KEY FK_COLONY_COUNTER;

ALTER TABLE EXOTIC_RESOURCES
DROP INDEX FK_EXOTIC_RESOURCES_COLONY,
DROP FOREIGN KEY FK_EXOTIC_RESOURCES_COLONY;

RENAME TABLE COLONY TO ESTABLISHMENT;

ALTER TABLE ESTABLISHMENT
ADD INDEX FK_ESTABLISHMENT_COUNTER (ID_COUNTER),
ADD CONSTRAINT FK_ESTABLISHMENT_COUNTER
FOREIGN KEY (ID_COUNTER)
REFERENCES COUNTER (ID);

ALTER TABLE ESTABLISHMENT
  ADD COLUMN TYPE VARCHAR(255);

UPDATE ESTABLISHMENT SET TYPE = 'COL' WHERE COLONY = 1;
UPDATE ESTABLISHMENT SET TYPE = 'TP' WHERE COLONY = 0;

ALTER TABLE ESTABLISHMENT
  DROP COLUMN COLONY;

ALTER TABLE EXOTIC_RESOURCES
  CHANGE ID_COLONY ID_ESTABLISHMENT BIGINT;

ALTER TABLE EXOTIC_RESOURCES
ADD INDEX FK_EXOTIC_RESOURCES_ESTABLISHMENT (ID_ESTABLISHMENT),
ADD CONSTRAINT FK_EXOTIC_RESOURCES_ESTABLISHMENT
FOREIGN KEY (ID_ESTABLISHMENT)
REFERENCES ESTABLISHMENT (ID);