ALTER TABLE R_COUNTRY
ADD COLUMN CULTURE VARCHAR(255);

ALTER TABLE R_COUNTRY
ADD COLUMN GEOPOLITICS_COUNTRY VARCHAR(255);

ALTER TABLE R_COUNTRY
ADD COLUMN GEOPOLITICS_BONUS INTEGER;

CREATE TABLE R_LIMIT (
  ID           BIGINT NOT NULL AUTO_INCREMENT,
  NUMBER       INTEGER,
  TYPE         VARCHAR(255),
  ID_R_COUNTRY BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE R_LIMIT
ADD INDEX FK_R_LIMIT_R_COUNTRY (ID_R_COUNTRY),
ADD CONSTRAINT FK_R_LIMIT_R_COUNTRY
FOREIGN KEY (ID_R_COUNTRY)
REFERENCES R_COUNTRY (ID);

CREATE TABLE R_BASIC_FORCE (
  ID           BIGINT NOT NULL AUTO_INCREMENT,
  NUMBER       INTEGER,
  TYPE         VARCHAR(255),
  ID_R_COUNTRY BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE R_BASIC_FORCE
ADD INDEX FK_R_BASIC_FORCE_R_COUNTRY (ID_R_COUNTRY),
ADD CONSTRAINT FK_R_BASIC_FORCE_R_COUNTRY
FOREIGN KEY (ID_R_COUNTRY)
REFERENCES R_COUNTRY (ID);

CREATE TABLE R_REINFORCEMENTS (
  ID           BIGINT NOT NULL AUTO_INCREMENT,
  NUMBER       INTEGER,
  TYPE         VARCHAR(255),
  ID_R_COUNTRY BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE R_REINFORCEMENTS
ADD INDEX FK_R_REINFORCEMENTS_R_COUNTRY (ID_R_COUNTRY),
ADD CONSTRAINT FK_R_REINFORCEMENTS_R_COUNTRY
FOREIGN KEY (ID_R_COUNTRY)
REFERENCES R_COUNTRY (ID);

