ALTER TABLE SIEGE
ADD COLUMN ID_WAR BIGINT NOT NULL,
ADD COLUMN PHASINGOFFENSIVE BIT;

ALTER TABLE SIEGE
ADD INDEX SIEGE_WAR (ID_WAR),
ADD CONSTRAINT SIEGE_WAR
FOREIGN KEY (ID_WAR)
REFERENCES WAR (ID);
