CREATE TABLE T_MNU (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  COUNTRY    VARCHAR(255),
  TYPE    VARCHAR(255),
  VALUE    INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE T_GOLD (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  PROVINCE    VARCHAR(255),
  VALUE    INTEGER,
  PRIMARY KEY (ID)
);