
ALTER TABLE SIEGE_COUNTER
DROP FOREIGN KEY SIEGE_COUNTER_SIEGE,
DROP FOREIGN KEY SIEGE_COUNTER_COUNTER;
DROP TABLE SIEGE_COUNTER;
ALTER TABLE SIEGE
DROP FOREIGN KEY FK_SIEGE_GAME;
DROP TABLE SIEGE;

CREATE TABLE SIEGE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ID_GAME BIGINT,
  TURN INTEGER,
  R_PROVINCE VARCHAR(255),
  STATUS VARCHAR(255),
  FORTRESSLEVEL INTEGER,
  BREACH BIT,
  BONUS INTEGER,
  UNDERMINEDIE INTEGER,
  UNDERMINERESULT VARCHAR(255),
  FORTRESSFALLS BIT,
  PHASING_LOSSESSELECTED BIT,
  PHASING_SIZE DOUBLE,
  PHASING_TECH VARCHAR(255),
  PHASING_MORAL INTEGER,
  PHASING_MODIFIERS_FIREMOD INTEGER DEFAULT 0,
  PHASING_MODIFIERS_FIRE INTEGER,
  PHASING_MODIFIERS_SHOCKMOD INTEGER DEFAULT 0,
  PHASING_MODIFIERS_SHOCK INTEGER,
  PHASING_LOSSES_ROUNDLOSS INTEGER DEFAULT 0,
  PHASING_LOSSES_THIRDLOSS INTEGER DEFAULT 0,
  PHASING_LOSSES_MORALELOSS INTEGER DEFAULT 0,
  NONPHASING_LOSSESSELECTED BIT,
  NONPHASING_SIZE DOUBLE,
  NONPHASING_TECH VARCHAR(255),
  NONPHASING_MORAL INTEGER,
  NONPHASING_MODIFIERS_FIREMOD INTEGER DEFAULT 0,
  NONPHASING_MODIFIERS_FIRE INTEGER,
  NONPHASING_MODIFIERS_SHOCKMOD INTEGER DEFAULT 0,
  NONPHASING_MODIFIERS_SHOCK INTEGER,
  NONPHASING_LOSSES_ROUNDLOSS INTEGER DEFAULT 0,
  NONPHASING_LOSSES_THIRDLOSS INTEGER DEFAULT 0,
  NONPHASING_LOSSES_MORALELOSS INTEGER DEFAULT 0,
  PRIMARY KEY (ID)
);

ALTER TABLE SIEGE
ADD INDEX FK_SIEGE_GAME (ID_GAME),
ADD CONSTRAINT FK_SIEGE_GAME
FOREIGN KEY (ID_GAME)
REFERENCES GAME (ID);

CREATE TABLE SIEGE_COUNTER (
  ID_SIEGE         BIGINT NOT NULL,
  ID_COUNTER  BIGINT NOT NULL,
  PHASING    BIT,
  PRIMARY KEY (ID_SIEGE, ID_COUNTER)
);

ALTER TABLE SIEGE_COUNTER
ADD INDEX SIEGE_COUNTER_SIEGE (ID_SIEGE),
ADD CONSTRAINT SIEGE_COUNTER_SIEGE
FOREIGN KEY (ID_SIEGE)
REFERENCES SIEGE (ID);

ALTER TABLE SIEGE_COUNTER
ADD INDEX SIEGE_COUNTER_COUNTER (ID_COUNTER),
ADD CONSTRAINT SIEGE_COUNTER_COUNTER
FOREIGN KEY (ID_COUNTER)
REFERENCES COUNTER (ID);