CREATE TABLE BATTLE (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  ID_GAME  BIGINT,
  TURN    INTEGER,
  R_PROVINCE    VARCHAR(255),
  PRIMARY KEY (ID)
);

ALTER TABLE BATTLE
ADD INDEX FK_BATTLE_GAME (ID_GAME),
ADD CONSTRAINT FK_BATTLE_GAME
FOREIGN KEY (ID_GAME)
REFERENCES GAME (ID);

CREATE TABLE SIEGE (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  ID_GAME  BIGINT,
  TURN    INTEGER,
  R_PROVINCE    VARCHAR(255),
  PRIMARY KEY (ID)
);

ALTER TABLE SIEGE
ADD INDEX FK_SIEGE_GAME (ID_GAME),
ADD CONSTRAINT FK_SIEGE_GAME
FOREIGN KEY (ID_GAME)
REFERENCES GAME (ID);