ALTER TABLE COUNTRY_ORDER
MODIFY COLUMN READY BIT DEFAULT b'0' NOT NULL;

UPDATE COUNTRY_ORDER SET ACTIVE = b'0' WHERE ACTIVE IS NULL;

ALTER TABLE COUNTRY_ORDER
MODIFY COLUMN ACTIVE BIT DEFAULT b'0' NOT NULL;

UPDATE STACK SET BESIEGED = b'0' WHERE BESIEGED IS NULL;

ALTER TABLE STACK
MODIFY COLUMN BESIEGED BIT DEFAULT b'0' NOT NULL;
