CREATE TABLE R_GEO_GROUP (
  ID     BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  R_PROVINCE VARCHAR(255),
  R_REGION VARCHAR(255),
  PRIMARY KEY (ID)
);

-- North America
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Labrador');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Terre-Neuve');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Hudson');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Rocheuses');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Alaska');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Oregon');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'California');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Nevada');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Arizona');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Kansas');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Texas');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Quebec');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Grands Lacs');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Illinois');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Iroquois');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Mississippi');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Carolina');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Virginia');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'America');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Acadie');

-- Caribbean (Florida is both North America and Caribbean)
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Florida');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Cuba');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Haiti');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Antilles');

-- South America
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Chichimeca');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Azteca');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Yucatan');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Panama');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Ecuador');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Venezuela');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Guyana');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Amazonia');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Inca');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Minas Gerais');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Paraguay');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Chili');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Patagonia');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Plata');

-- Brazil
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Belem');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Recife');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Rio');

-- Malouines
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('AMERICA', 'Malouines');