CREATE TABLE R_PROVINCE_ROTW (
  ID BIGINT NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE R_PROVINCE_ROTW
ADD INDEX FK_R_PROVINCE_ROTW_R_PROVINCE (ID),
ADD CONSTRAINT FK_R_PROVINCE_ROTW_R_PROVINCE
FOREIGN KEY (ID)
REFERENCES R_PROVINCE (ID);