ALTER TABLE COUNTRY
ADD COLUMN DTI INTEGER;

ALTER TABLE COUNTRY
ADD COLUMN DTI_MAX INTEGER;

ALTER TABLE COUNTRY
ADD COLUMN FTI INTEGER;

ALTER TABLE COUNTRY
ADD COLUMN FTI_MAX INTEGER;

CREATE TABLE T_TRADE (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  COUNTRY_VALUE    INTEGER,
  MIN_VALUE    INTEGER,
  MAX_VALUE    INTEGER,
  VALUE    INTEGER,
  FOREIGN_TRADE BIT,
  PRIMARY KEY (ID)
);