ALTER TABLE BATTLE
ADD COLUMN ATTACKER_FORCES BIT;

ALTER TABLE BATTLE
ADD COLUMN DEFENDER_FORCES BIT;

ALTER TABLE BATTLE
ADD COLUMN STATUS VARCHAR(255);

CREATE TABLE BATTLE_COUNTER (
  ID_BATTLE         BIGINT NOT NULL,
  ID_COUNTER  BIGINT NOT NULL,
  ATTACKER    BIT,
  PRIMARY KEY (ID_BATTLE, ID_COUNTER)
);

ALTER TABLE BATTLE_COUNTER
ADD INDEX BATTLE_COUNTER_BATTLE (ID_BATTLE),
ADD CONSTRAINT BATTLE_COUNTER_BATTLE
FOREIGN KEY (ID_BATTLE)
REFERENCES BATTLE (ID);

ALTER TABLE BATTLE_COUNTER
ADD INDEX BATTLE_COUNTER_COUNTER (ID_COUNTER),
ADD CONSTRAINT BATTLE_COUNTER_COUNTER
FOREIGN KEY (ID_COUNTER)
REFERENCES COUNTER (ID);