ALTER TABLE GAME
ADD COLUMN MED_CC_COUNTRY VARCHAR(255);

ALTER TABLE GAME
ADD COLUMN ORIENT_CC_COUNTRY VARCHAR(255);

ALTER TABLE GAME
ADD COLUMN ATL_CC_COUNTRY VARCHAR(255);

ALTER TABLE GAME
ADD COLUMN INDIAN_CC_COUNTRY VARCHAR(255);

ALTER TABLE GAME
ADD COLUMN ST_PETER_PROVINCE VARCHAR(255);
