ALTER TABLE STACK
ADD COLUMN R_PROVINCE VARCHAR(255);

UPDATE STACK
SET R_PROVINCE = (SELECT NAME
                  FROM PROVINCE
                  WHERE ID = ID_PROVINCE);

ALTER TABLE STACK
DROP FOREIGN KEY FK_STACK_PROVINCE;

ALTER TABLE STACK
DROP INDEX FK_STACK_PROVINCE;

ALTER TABLE STACK
DROP COLUMN ID_PROVINCE;