CREATE TABLE R_COUNTRY (
  ID   BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE R_PROVINCE (
  ID      BIGINT NOT NULL AUTO_INCREMENT,
  NAME    VARCHAR(255),
  TERRAIN VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE R_PROVINCE_EU (
  INCOME       INTEGER,
  PORT         BIT,
  PRAESIDIABLE BIT,
  ID           BIGINT NOT NULL,
  R_COUNTRY    VARCHAR(255),
  PRIMARY KEY (ID)
);


ALTER TABLE R_PROVINCE_EU
ADD INDEX FK_R_PROVINCE_R_EU_PROVINCE (ID),
ADD CONSTRAINT FK_R_PROVINCE_R_EU_PROVINCE
FOREIGN KEY (ID)
REFERENCES R_PROVINCE (ID);

ALTER TABLE R_PROVINCE
ADD CONSTRAINT UK_R_PROVINCE_NAME UNIQUE (NAME);


CREATE TABLE R_BORDER (
  ID                 BIGINT NOT NULL AUTO_INCREMENT,
  TYPE               VARCHAR(255),
  ID_R_PROVINCE_FROM BIGINT,
  ID_R_PROVINCE_TO   BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE R_BORDER
ADD INDEX FK_R_BORDER_R_PROVINCE_FROM (ID_R_PROVINCE_FROM),
ADD CONSTRAINT FK_R_BORDER_R_PROVINCE_FROM
FOREIGN KEY (ID_R_PROVINCE_FROM)
REFERENCES R_PROVINCE (ID);

ALTER TABLE R_BORDER
ADD INDEX FK_R_BORDER_R_PROVINCE_TO (ID_R_PROVINCE_TO),
ADD CONSTRAINT FK_R_BORDER_R_PROVINCE_TO
FOREIGN KEY (ID_R_PROVINCE_TO)
REFERENCES R_PROVINCE (ID);


INSERT INTO R_PROVINCE SELECT *
                       FROM PROVINCE;
INSERT INTO R_PROVINCE_EU SELECT *
                          FROM PROVINCE_EU;
INSERT INTO R_BORDER SELECT *
                     FROM BORDER;


ALTER TABLE PROVINCE
DROP INDEX UK_PROVINCE_NAME;

ALTER TABLE PROVINCE_EU
DROP FOREIGN KEY FK_PROVINCE_EU_PROVINCE;
ALTER TABLE PROVINCE_EU
DROP INDEX FK_PROVINCE_EU_PROVINCE;

ALTER TABLE BORDER
DROP FOREIGN KEY FK_BORDER_PROVINCE_FROM;
ALTER TABLE BORDER
DROP INDEX FK_BORDER_PROVINCE_FROM;

ALTER TABLE BORDER
DROP FOREIGN KEY FK_BORDER_PROVINCE_TO;
ALTER TABLE BORDER
DROP INDEX FK_BORDER_PROVINCE_TO;


DROP TABLE BORDER;
DROP TABLE PROVINCE_EU;
DROP TABLE PROVINCE;
