CREATE TABLE WAR (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  ID_GAME  BIGINT,
  TYPE VARCHAR(255),
  PRIMARY KEY (ID)
);

ALTER TABLE WAR
ADD INDEX FK_WAR_GAME (ID_GAME),
ADD CONSTRAINT FK_WAR_GAME
FOREIGN KEY (ID_GAME)
REFERENCES GAME (ID);

CREATE TABLE WAR_COUNTRY (
  ID_WAR BIGINT NOT NULL,
  R_COUNTRY     VARCHAR(255) NOT NULL,
  OFFENSIVE BIT,
  IMPLICATION VARCHAR(255),
  PRIMARY KEY (ID_WAR, R_COUNTRY)
);

ALTER TABLE WAR_COUNTRY
ADD INDEX WAR_COUNTRY_WAR (ID_WAR),
ADD CONSTRAINT WAR_COUNTRY_WAR
FOREIGN KEY (ID_WAR)
REFERENCES WAR (ID);

CREATE TABLE COUNTRY_ORDER (
  ID_GAME BIGINT NOT NULL,
  R_COUNTRY     VARCHAR(255) NOT NULL,
  GAME_STATUS VARCHAR(255),
  POSITION INTEGER,
  PRIMARY KEY (ID_GAME, R_COUNTRY, GAME_STATUS)
);

ALTER TABLE COUNTRY_ORDER
ADD INDEX COUNTRY_ORDER_GAME (ID_GAME),
ADD CONSTRAINT COUNTRY_ORDER_GAME
FOREIGN KEY (ID_GAME)
REFERENCES GAME (ID);