ALTER TABLE SIEGE_COUNTER
  ADD COLUMN COUNTRY VARCHAR(255),
  ADD COLUMN `TYPE` VARCHAR(255),
  DROP FOREIGN KEY SIEGE_COUNTER_COUNTER;

UPDATE SIEGE_COUNTER SC
  INNER JOIN COUNTER C ON SC.ID_COUNTER = C.ID
SET SC.COUNTRY = C.R_COUNTRY, SC.TYPE = C.TYPE;