CREATE TABLE COMPETITION (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  ID_GAME  BIGINT,
  TURN    INTEGER,
  TYPE    VARCHAR(255),
  R_PROVINCE    VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE COMPETITION_ROUND (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  R_COUNTRY VARCHAR(255),
  ROUND INTEGER,
  COLUNM    INTEGER,
  DIE    INTEGER,
  SECONDARY_DIE INTEGER,
  RESULT    VARCHAR(255),
  SECONDARY_RESULT BIT,
  ID_COMPETITION BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE COMPETITION
ADD INDEX FK_COMPETITION_GAME (ID_GAME),
ADD CONSTRAINT FK_COMPETITION_GAME
FOREIGN KEY (ID_GAME)
REFERENCES GAME (ID);

ALTER TABLE COMPETITION_ROUND
ADD INDEX FK_COMPETITION_ROUND_COMPETITION (ID_COMPETITION),
ADD CONSTRAINT FK_COMPETITION_ROUND_COMPETITION
FOREIGN KEY (ID_COMPETITION)
REFERENCES COMPETITION (ID);