CREATE TABLE T_EXCHEQUER (
  ID     BIGINT NOT NULL AUTO_INCREMENT,
  RESULT VARCHAR(255),
  REGULAR    INTEGER,
  PRESTIGE    INTEGER,
  NATLOAN    INTEGER,
  INTERLOAN    INTEGER,
  PRIMARY KEY (ID)
);