CREATE TABLE ADMINISTRATIVE_ACTION (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  ID_COUNTRY  BIGINT,
  TURN    INTEGER,
  TYPE    VARCHAR(255),
  COST    INTEGER,
  COLUNM    INTEGER,
  BONUS    INTEGER,
  DIE    INTEGER,
  RESULT    VARCHAR(255),
  STATUS    VARCHAR(255),
  ID_OBJECT BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE ADMINISTRATIVE_ACTION
ADD INDEX FK_ADMINISTRATIVE_ACTION_COUNTRY (ID_COUNTRY),
ADD CONSTRAINT FK_ADMINISTRATIVE_ACTION_COUNTRY
FOREIGN KEY (ID_COUNTRY)
REFERENCES COUNTRY (ID);