CREATE TABLE C_ROOM (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  ID_GAME    BIGINT,
  ID_COUNTRY BIGINT,
  NAME       VARCHAR(255),
  PRIMARY KEY (ID)
);

ALTER TABLE C_ROOM
ADD INDEX FK_C_ROOM_GAME (ID_GAME),
ADD CONSTRAINT FK_C_ROOM_GAME
FOREIGN KEY (ID_GAME)
REFERENCES GAME (ID);

ALTER TABLE C_ROOM
ADD INDEX FK_C_ROOM_COUNTRY (ID_COUNTRY),
ADD CONSTRAINT FK_C_ROOM_COUNTRY
FOREIGN KEY (ID_COUNTRY)
REFERENCES COUNTRY (ID);

ALTER TABLE C_ROOM
ADD CONSTRAINT UK_C_ROOM
UNIQUE (ID_GAME, NAME);

CREATE TABLE C_PRESENT (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  ID_C_ROOM  BIGINT,
  ID_COUNTRY BIGINT,
  PRESENT    BIT,
  VISIBLE    BIT,
  PRIMARY KEY (ID)
);

ALTER TABLE C_PRESENT
ADD INDEX FK_C_PRESENT_C_ROOM (ID_C_ROOM),
ADD CONSTRAINT FK_C_PRESENT_C_ROOM
FOREIGN KEY (ID_C_ROOM)
REFERENCES C_ROOM (ID);

ALTER TABLE C_PRESENT
ADD INDEX FK_C_PRESENT_COUNTRY (ID_COUNTRY),
ADD CONSTRAINT FK_C_PRESENT_COUNTRY
FOREIGN KEY (ID_COUNTRY)
REFERENCES COUNTRY (ID);

CREATE TABLE C_MESSAGE (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  ID_COUNTRY BIGINT,
  MESSAGE    VARCHAR(4096),
  DATE_SENT  TIMESTAMP,
  PRIMARY KEY (ID)
);

ALTER TABLE C_MESSAGE
ADD INDEX FK_C_MESSAGE_COUNTRY (ID_COUNTRY),
ADD CONSTRAINT FK_C_MESSAGE_COUNTRY
FOREIGN KEY (ID_COUNTRY)
REFERENCES COUNTRY (ID);


CREATE TABLE C_CHAT (
  ID           BIGINT NOT NULL AUTO_INCREMENT,
  ID_C_ROOM    BIGINT,
  ID_COUNTRY   BIGINT,
  ID_C_MESSAGE BIGINT,
  DATE_READ    TIMESTAMP,
  PRIMARY KEY (ID)
);

ALTER TABLE C_CHAT
ADD INDEX FK_C_CHAT_C_ROOM (ID_C_ROOM),
ADD CONSTRAINT FK_C_CHAT_C_ROOM
FOREIGN KEY (ID_C_ROOM)
REFERENCES C_ROOM (ID);

ALTER TABLE C_CHAT
ADD INDEX FK_C_CHAT_COUNTRY (ID_COUNTRY),
ADD CONSTRAINT FK_C_CHAT_COUNTRY
FOREIGN KEY (ID_COUNTRY)
REFERENCES COUNTRY (ID);

ALTER TABLE C_CHAT
ADD INDEX FK_C_CHAT_C_MESSAGE (ID_C_MESSAGE),
ADD CONSTRAINT FK_C_CHAT_C_MESSAGE
FOREIGN KEY (ID_C_MESSAGE)
REFERENCES C_MESSAGE (ID);

CREATE TABLE C_ROOM_GLOBAL (
  ID      BIGINT NOT NULL AUTO_INCREMENT,
  ID_GAME BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE C_ROOM_GLOBAL
ADD INDEX FK_C_ROOM_GLOBAL_GAME (ID_GAME),
ADD CONSTRAINT FK_C_ROOM_GLOBAL_GAME
FOREIGN KEY (ID_GAME)
REFERENCES GAME (ID);

CREATE TABLE C_MESSAGE_GLOBAL (
  ID               BIGINT NOT NULL AUTO_INCREMENT,
  ID_C_ROOM_GLOBAL BIGINT,
  ID_COUNTRY       BIGINT,
  MESSAGE          VARCHAR(4096),
  DATE_SENT        TIMESTAMP,
  PRIMARY KEY (ID)
);

ALTER TABLE C_MESSAGE_GLOBAL
ADD INDEX FK_C_MESSAGE_GLOBAL_C_ROOM_GLOBAL (ID_C_ROOM_GLOBAL),
ADD CONSTRAINT FK_C_MESSAGE_GLOBAL_C_ROOM_GLOBAL
FOREIGN KEY (ID_C_ROOM_GLOBAL)
REFERENCES C_ROOM_GLOBAL (ID);

ALTER TABLE C_MESSAGE_GLOBAL
ADD INDEX FK_C_MESSAGE_GLOBAL_COUNTRY (ID_COUNTRY),
ADD CONSTRAINT FK_C_MESSAGE_GLOBAL_COUNTRY
FOREIGN KEY (ID_COUNTRY)
REFERENCES COUNTRY (ID);