ALTER TABLE COUNTRY_ORDER
DROP COLUMN R_COUNTRY;

ALTER TABLE COUNTRY_ORDER
ADD COLUMN ID_COUNTRY BIGINT;

ALTER TABLE COUNTRY_ORDER
ADD INDEX FK_COUNTRY_ORDER_COUNTRY (ID_COUNTRY),
ADD CONSTRAINT FK_COUNTRY_ORDER_COUNTRY
FOREIGN KEY (ID_COUNTRY)
REFERENCES COUNTRY (ID);