-- Middle East
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Nedj');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Oman');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Aden');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Ormus');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Afghanistan');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Balouchistan');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Aral');

-- India
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Delhi');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Ayutthaya');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Bengale');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Gujarat');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Pendjab');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Indus');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Orissa');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Gondwana');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Mumbai');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Hyderabad');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Malabar');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Karnatika');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Singala');

-- Indochina
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Birmanie');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Malacca');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Ayutthaya');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Dai Viet');

-- Extreme Orient
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Japon');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Formose');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Corea');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Mandchourie');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Pekin');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Nankin');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Canton');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Philippines');

-- Indonesia
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Sumatra');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Java');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Borneo');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Celebes');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Iles de la Sonde');
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Iles aux epices');

-- Oceania
INSERT INTO R_GEO_GROUP (NAME, R_REGION)
VALUES ('ASIA', 'Oceania');




INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sNoire W');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sNoire E');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sMarmara');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sEgee');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sLevantin');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sAdriatique');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sIonienne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sThyrrenienne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sGabes');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sLion');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sAlboran');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('MEDITERRANEAN SEA', 'sAlger');