CREATE TABLE MONARCH (
  ID         BIGINT NOT NULL,
  BEGIN      INTEGER,
  END        INTEGER,
  ADM        INTEGER,
  DIP        INTEGER,
  MIL        INTEGER,
  MIL_AVG    INTEGER,
  ID_COUNTRY BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE MONARCH
ADD INDEX FK_MONARCH_COUNTRY (ID_COUNTRY),
ADD CONSTRAINT FK_MONARCH_COUNTRY
FOREIGN KEY (ID_COUNTRY)
REFERENCES COUNTRY (ID);

ALTER TABLE COUNTRY
ADD COLUMN ID_MONARCH BIGINT;

ALTER TABLE COUNTRY
ADD INDEX FK_COUNTRY_MONARCH (ID_MONARCH),
ADD CONSTRAINT FK_COUNTRY_MONARCH
FOREIGN KEY (ID_MONARCH)
REFERENCES MONARCH (ID);


