ALTER TABLE BATTLE_COUNTER
  ADD COLUMN COUNTRY VARCHAR(255),
  ADD COLUMN `TYPE` VARCHAR(255),
  DROP FOREIGN KEY BATTLE_COUNTER_COUNTER;

UPDATE BATTLE_COUNTER BC
  INNER JOIN COUNTER C ON BC.ID_COUNTER = C.ID
SET BC.COUNTRY = C.R_COUNTRY, BC.TYPE = C.TYPE;