ALTER TABLE COUNTRY
  ADD COLUMN ID_GAME BIGINT;

UPDATE COUNTRY SET ID_GAME = 1;

ALTER TABLE COUNTRY
    ADD INDEX FK_COUNTRY_GAME (ID_GAME),
    ADD CONSTRAINT FK_COUNTRY_GAME
    FOREIGN KEY (ID_GAME)
    REFERENCES GAME (ID);