DELETE FROM R_COUNTRY_PROVINCE_EU_CAPITALS;
DELETE FROM R_COUNTRY_PROVINCE_EU;
DELETE FROM R_COUNTRY;
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('kazan', 'MINOR', 'SUNNITE', '4', '40', '1', '1', '4', '3', '10', '12', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'kazan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kazan’'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'kazan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Tatarstan'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'kazan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Cheboksary'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'kazan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Mordoviya'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'kazan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Samara'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'kazan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Idel Bolgarstany'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('hesse', 'MINOR', 'PROTESTANT', '7', '20', '1', '3', '3', '6', null, '14', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hesse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Hessen'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hesse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Nassau'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('moldavie', 'MINOR', 'ORTHODOX', '8', '50', '1', '1', '1', '5', '10', '10', 'Orthodoxe', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'moldavie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Moldova'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'moldavie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Basarabia'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('saint-empire', 'VIRTUAL', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'saint-empire'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Franken'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('parliament', 'VIRTUAL', 'PROTESTANT', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'parliament'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'East Anglia'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('hollande', 'MINORMAJOR', 'PROTESTANT', '20', '10', '3', '5', '9', null, null, '12', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Friesland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Gelderland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Holland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Overijssel'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Utrecht'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Zeeland'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Vliflandie', 'REVOLT', 'PROTESTANT', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vliflandie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Ingermanland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vliflandie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Eesti'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vliflandie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Livonija'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vliflandie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kurland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vliflandie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Memel'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('pologne', 'MINORMAJOR', 'CATHOLIC', '18', '80', '1', '1', '2', null, null, '12', 'Orthodoxe', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('vijayanagar', 'ROTW', 'OTHER', null, null, null, null, null, null, null, '14', 'ROTW', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Vlithuanie', 'REVOLT', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vlithuanie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Polacak'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vlithuanie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Severia'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vlithuanie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Baltarusija'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vlithuanie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lietuvą'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vlithuanie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Žemaitija'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vlithuanie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Smolenską'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vlithuanie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Prypeć'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('german-empire', 'VIRTUAL', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'german-empire'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Franken'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('aden', 'ROTW', 'SUNNITE', null, null, null, null, null, null, null, '14', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('irak', 'MINOR', 'SUNNITE', '6', '20', '1', '1', '2', '3', '10', '6', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'irak'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'al-‛Irāq'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'irak'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'al-Başrah'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'irak'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Dijlah'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Vbelgique', 'REVOLT', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vbelgique'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Vlaanderen'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vbelgique'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Flandre'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vbelgique'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Hainaut'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vbelgique'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Brabant'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vbelgique'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Limburg'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vbelgique'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Luxemburg'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vbelgique'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Artois'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Hboheme', 'HAB', 'PROTESTANT', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hboheme'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bohème'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hboheme'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Silésie'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hboheme'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Morava'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hboheme'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lausitz'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Hnaples', 'HAB', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hnaples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Campania'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hnaples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Abruzzo'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hnaples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Basilicata'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hnaples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Puglia'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hnaples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Calabria'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hnaples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Sicilia'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hnaples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Palermo'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hnaples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Saldígna'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('genes', 'MINOR', 'CATHOLIC', '7', '30', '1', '2', '3', '4', null, '17', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'genes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Liguria'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'genes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Corsica'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('transylvanie', 'REVOLT', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Orthodoxe', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'transylvanie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Erdély'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'transylvanie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Marosz'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('savoie', 'MINOR', 'CATHOLIC', '5', '40', '1', '2', '3', '8', null, '9', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'savoie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Savoia'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'savoie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Nice'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'savoie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bresse'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('habsbourg', 'MINORMAJOR', 'CATHOLIC', '8', '30', '2', '3', '2', null, null, '18', 'Latin', b'1', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'habsbourg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Österreich'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'habsbourg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Tirol'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'habsbourg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Salzburg'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'habsbourg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Steiermark'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'habsbourg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kärnten'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'habsbourg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Slovenija'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'habsbourg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Trentino'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('gujarat', 'ROTW', 'SUNNITE', null, null, null, null, null, null, null, '11', 'ROTW', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('brandebourg', 'MINOR', 'PROTESTANT', '3', '70', '2', '3', '4', null, null, '16', 'Latin', b'1', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'brandebourg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Brandenburg'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'brandebourg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Altmark'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'brandebourg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Neumark'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('bade', 'MINOR', 'CATHOLIC', '6', '20', '1', '2', '4', null, null, '14', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'bade'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Baden'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('tripoli', 'MINOR', 'SUNNITE', '8', '50', '1', '1', '1', '2', '10', '8', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'tripoli'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Ṭarablūs'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('iroquois', 'ROTW', 'OTHER', null, null, null, null, null, null, null, '11', 'ROTW', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('ukraine', 'MINOR', 'ORTHODOX', '6', '40', '1', '3', '4', '3', '10', '14', 'Orthodoxe', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Don'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Donets'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Poltava'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Ukraïnya'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Podillya'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Zaporizhzhya'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('natives', 'VIRTUAL', 'OTHER', null, null, null, null, null, null, null, '0', 'Amerique', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Hmilan', 'HAB', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hmilan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lombardia'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('teutoniques1', 'MINOR', 'CATHOLIC', '4', '60', '1', '2', '3', '4', '10', '14', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'teutoniques1'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Livonija'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'teutoniques1'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Eesti'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'teutoniques1'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kurland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'teutoniques1'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Memel'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('teutoniques2', 'MINOR', 'CATHOLIC', '4', '60', '1', '2', '3', '4', '10', '14', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'teutoniques2'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Preußen'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'teutoniques2'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Hinterpommern'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'teutoniques2'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Vorpommern'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('hongrie', 'MINOR', 'CATHOLIC', '12', '50', '1', '1', '3', null, null, '17', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Magyarország'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Szlovákia'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kárpátok'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bukovina'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Balaton'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Pécs'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Erdély'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Marosz'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Carniola'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Hrvatska'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Banat'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kapela'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('hanovre', 'MINOR', 'PROTESTANT', '12', '20', '1', '2', '3', '6', null, '15', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hanovre'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Hannover'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hanovre'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Osnabrück'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('hanse', 'MINOR', 'PROTESTANT', '4', '20', '2', '3', '5', '8', null, '14', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hanse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bremen'));
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hanse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lübeck'));
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hanse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Holstein'));
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'hanse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Mecklenburg'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('montferrat', 'MINOR', 'CATHOLIC', '6', '30', '4', '2', '2', null, null, '12', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'montferrat'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Monferrato'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Hhongrie', 'HAB', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Magyarország'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Szlovákia'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kárpátok'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bukovina'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Balaton'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Pécs'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Erdély'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Marosz'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Carniola'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Hrvatska'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Banat'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Hhongrie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kapela'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('liege', 'MINOR', 'CATHOLIC', '8', '50', '3', '2', '4', '4', '4', '16', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'liege'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Liège'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('royalistes', 'VIRTUAL', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'royalistes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Midlands'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'royalistes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Cornwall'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'royalistes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Durham'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'royalistes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Connacht'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'royalistes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Mumhan'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'royalistes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Laighean'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'royalistes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Brega'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'royalistes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Uladh'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('afghans', 'ROTW', 'SUNNITE', null, null, null, null, null, null, null, '14', 'ROTW', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('algerie', 'MINOR', 'SUNNITE', '6', '40', '1', '1', '2', '3', '10', '15', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'algerie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'al-Jaza’ir'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'algerie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'al-’Aṭlas'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'algerie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Wahrān'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'algerie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'al-Qaba’il'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'algerie'), (SELECT ID FROM R_PROVINCE WHERE NAME = '’Arīs'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'algerie'), (SELECT ID FROM R_PROVINCE WHERE NAME = '‛Annābah'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('portugal', 'MINORMAJOR', 'CATHOLIC', '10', '30', '1', '2', '4', null, null, '16', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('cyrenaique', 'MINOR', 'SUNNITE', '6', '60', '1', '1', '1', '3', '5', '16', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'cyrenaique'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Barqah'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('milan', 'MINOR', 'CATHOLIC', '14', '50', '4', '5', '2', null, null, '10', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'milan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lombardia'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('cosaquesdon', 'MINOR', 'SUNNITE', '6', '40', '1', '3', '4', '3', '10', '14', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'cosaquesdon'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Donets'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'cosaquesdon'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Don'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'cosaquesdon'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Dikoe Pole'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('arabie', 'MINOR', 'SUNNITE', '4', '50', '1', '1', '2', '3', '10', '17', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'arabie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'al-’arabiyah'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'arabie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'al-Ā’urdunn'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'arabie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'an-Nafūd'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('ormus', 'ROTW', 'SHIITE', null, null, null, null, null, null, null, '5', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('palatinat', 'MINOR', 'PROTESTANT', '10', '40', '2', '3', '4', null, null, '9', 'Latin', b'1', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'palatinat'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Pfalz'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'palatinat'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'OberPfalz'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('papaute', 'MINOR', 'CATHOLIC', '10', '10', '1', '1', '1', '10', null, '8', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'papaute'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lazio'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'papaute'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Romagna'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'papaute'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Marche'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'papaute'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Umbria'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('pirates', 'VIRTUAL', 'OTHER', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('venise', 'MINORMAJOR', 'CATHOLIC', '12', '20', '3', '4', '7', null, null, '16', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('danemark', 'MINOR', 'PROTESTANT', '6', '30', '1', '2', '5', null, null, '10', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'danemark'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Sjælland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'danemark'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Trøndelag'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'danemark'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Vestfold'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'danemark'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Østlandet'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'danemark'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Västergotland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'danemark'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Gotland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'danemark'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Skåne'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'danemark'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Slesvig'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'danemark'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Jylland'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('aceh', 'ROTW', 'SUNNITE', null, null, null, null, null, null, null, '16', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('tunisie', 'MINOR', 'SUNNITE', '4', '30', '1', '1', '1', '2', '10', '8', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'tunisie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Tūnis'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'tunisie'), (SELECT ID FROM R_PROVINCE WHERE NAME = '’Afrīqiyah'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('damas', 'MINOR', 'SHIITE', '12', '20', '1', '1', '1', '8', '15', '8', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'damas'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Sūriyah'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'damas'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Terra Sancta'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'damas'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lubnān'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'damas'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Ĥalab'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('mamelouks', 'MINOR', 'SHIITE', '12', '20', '1', '1', '1', '8', '15', '8', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'mamelouks'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Mişr'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'mamelouks'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Ṭubruq'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'mamelouks'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'an-Nīl'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'mamelouks'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Deltā'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'mamelouks'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'al-Nūbah'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'mamelouks'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Sīnā’'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'mamelouks'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Šallāl'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Vnorvege', 'REVOLT', 'PROTESTANT', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vnorvege'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Trøndelag'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vnorvege'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Vestfold'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vnorvege'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Østlandet'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('inca', 'ROTW', 'OTHER', null, null, null, null, null, null, null, '16', 'Amerique', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('alsace', 'MINOR', 'CATHOLIC', '8', '50', '1', '2', '4', '8', null, '16', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'alsace'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Alsace'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('perse', 'MINOR', 'SHIITE', '16', '10', '3', '4', '7', null, null, '5', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Pārs'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Daġestān'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Wān'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Šīrwān'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kordistān'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Azarbāyadjān'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kermānšāh'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Eşfahān'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Mešhed'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bam'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'perse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Arménie'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('bourgogne', 'MINOR', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'bourgogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Vlaanderen'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'bourgogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Flandre'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'bourgogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Hainaut'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'bourgogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Brabant'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'bourgogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Limburg'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'bourgogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Luxemburg'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'bourgogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Franche-Comté'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'bourgogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Artois'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('valachie', 'MINOR', 'ORTHODOX', '2', '50', '1', '1', '1', '5', '10', '16', 'Orthodoxe', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'valachie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Valahia'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('siberie', 'ROTW', 'OTHER', null, null, null, null, null, null, null, '11', 'ROTW', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Virlande', 'REVOLT', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Virlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Mumhan'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Virlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Laighean'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Virlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Connacht'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Virlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Brega'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Virlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Uladh'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('suisse', 'MINOR', 'CATHO_PROT', '2', '50', '7', '10', null, null, null, '9', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suisse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Schweiz'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suisse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Graubunden'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('astrakhan', 'MINOR', 'SUNNITE', '6', '40', '1', '3', '4', '3', '10', '14', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'astrakhan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Astrakhan'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'astrakhan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Terek'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('usa', 'MINOR', 'CATHO_PROT', '5', '50', '10', null, null, null, null, '10', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Vcatalogne', 'REVOLT', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vcatalogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Catalunya'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vcatalogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Pirineos'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vcatalogne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Rosseló'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('wurtemberg', 'MINOR', 'CATHOLIC', '8', '30', '1', '4', '5', null, null, '14', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'wurtemberg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Würtemberg'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'wurtemberg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Schwaben'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('courlande', 'REVOLT', 'PROTESTANT', '5', '60', '1', '2', '4', '6', null, '6', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'courlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Livonija'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'courlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kurland'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('chevaliers', 'MINOR', 'CATHOLIC', '2', '60', '1', '2', '3', '2', '10', '18', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'chevaliers'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Rhodos'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Vukraine', 'REVOLT', 'ORTHODOX', null, null, null, null, null, null, null, '0', 'Orthodoxe', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Don'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Donets'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Poltava'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Ukraïnya'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Podillya'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vukraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Zaporizhzhya'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('saxe', 'MINOR', 'PROTESTANT', '6', '30', '1', '3', '4', null, null, '11', 'Latin', b'1', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'saxe'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Sachsen'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'saxe'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Anhalt'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('suede', 'MINORMAJOR', 'PROTESTANT', '8', '40', '1', '2', '4', null, null, '15', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suede'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Svealand'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suede'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Småland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suede'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Jämtland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suede'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Gästrikland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suede'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bergslagen'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suede'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Finland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suede'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Tavastland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suede'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Nyland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suede'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Karelen'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'suede'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kexholm'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Veastprussia', 'REVOLT', 'PROTESTANT', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Veastprussia'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Memel'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Veastprussia'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Preußen'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Veastprussia'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kurland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Veastprussia'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Danzig'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('hyderabad', 'ROTW', 'SUNNITE', null, null, null, null, null, null, null, '11', 'ROTW', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('brunswick', 'MINOR', 'PROTESTANT', '8', '40', '4', '3', '3', null, null, '14', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'brunswick'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Braunschweig'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('berg', 'MINOR', 'PROTESTANT', '4', '30', '2', '2', '4', '8', null, '14', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'berg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Berg'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('mogol', 'ROTW', 'SHIITE', null, null, null, null, null, null, null, '11', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('cologne', 'MINOR', 'CATHOLIC', '8', '20', '1', '2', '3', '8', null, '12', 'Latin', b'1', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'cologne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Köln'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('naples', 'MINOR', 'CATHOLIC', '4', '50', '2', '4', '5', '8', null, '10', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'naples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Campania'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'naples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Abruzzo'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'naples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Basilicata'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'naples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Puglia'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'naples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Calabria'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'naples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Sicilia'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'naples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Palermo'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'naples'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Saldígna'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('maroc', 'MINOR', 'SUNNITE', '4', '20', '1', '1', '2', '3', '10', '15', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'maroc'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Jebel Tubqāl'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'maroc'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'al-Maġrib'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'maroc'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'er-Rif'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'maroc'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'as-Sūs'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('parme', 'MINOR', 'CATHOLIC', '8', '30', '1', '2', '4', '8', null, '9', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'parme'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Parma'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('grenade', 'REVOLT', 'SUNNITE', null, null, null, null, null, null, null, '0', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'grenade'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Granada'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'grenade'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'La Mancha'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'grenade'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Murcia'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'grenade'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Córdoba'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('boheme', 'MINOR', 'PROTESTANT', '15', '20', '1', '3', '3', '5', '15', '15', 'Latin', b'1', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'boheme'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bohème'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'boheme'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Silésie'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'boheme'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Morava'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'boheme'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lausitz'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('lorraine', 'MINOR', 'CATHOLIC', '8', '50', '1', '2', '4', '8', null, '16', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'lorraine'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lorraine'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('georgie', 'MINOR', 'ORTHODOX', '8', '40', '4', '3', '3', null, null, '14', 'Orthodoxe', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'georgie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Géorgie'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'georgie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kuban'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('ryazan', 'MINOR', 'ORTHODOX', '8', '50', '1', '1', '1', '5', '5', '14', 'Orthodoxe', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ryazan'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Ryazan’'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('japon', 'ROTW', 'OTHER', null, null, null, null, null, null, null, '11', 'ROTW', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Vhollande', 'REVOLT', 'PROTESTANT', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vhollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Friesland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vhollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Gelderland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vhollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Holland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vhollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Overijssel'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vhollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Utrecht'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vhollande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Zeeland'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('baviere', 'MINOR', 'CATHOLIC', '10', '20', '2', '4', '6', null, null, '16', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'baviere'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bayern'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('oman', 'ROTW', 'SUNNITE', null, null, null, null, null, null, null, '14', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('provincesne', 'MINOR', 'PROTESTANT', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'provincesne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Friesland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'provincesne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Gelderland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'provincesne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Holland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'provincesne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Overijssel'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'provincesne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Utrecht'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'provincesne'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Zeeland'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('huguenots', 'VIRTUAL', 'PROTESTANT', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'huguenots'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Caux'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'huguenots'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Touraine'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'huguenots'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Poitou'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'huguenots'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Quercy'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'huguenots'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Guyenne'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'huguenots'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Béarn'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'huguenots'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Languedoc'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'huguenots'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Cévennes'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'huguenots'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Dauphiné'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('soudan', 'ROTW', 'SUNNITE', null, null, null, null, null, null, null, '11', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('pskov', 'MINOR', 'ORTHODOX', '8', '50', '1', '1', '1', '5', '5', '14', 'Orthodoxe', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'pskov'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Pskov'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('mazovie', 'MINOR', 'CATHOLIC', '4', '60', '1', '1', '1', '3', '6', '16', 'null', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'mazovie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Mazowia'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('modene', 'MINOR', 'CATHOLIC', '9', '30', '1', '2', '4', '8', null, '8', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'modene'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Modena'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('toscane', 'MINOR', 'CATHOLIC', '6', '50', '1', '3', '3', '6', '10', '14', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'toscane'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Toscana'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'toscane'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Siena'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('crimee', 'MINOR', 'SUNNITE', '6', '60', '1', '1', '3', '5', '10', '10', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'crimee'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Qırım'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'crimee'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Hacıbey'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'crimee'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Zaporizhzhya'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'crimee'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Azov'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('ecosse', 'MINOR', 'PROTESTANT', '8', '40', '1', '1', '3', '4', null, '16', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ecosse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lothian'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ecosse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Highlands'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ecosse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Alba'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ecosse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Moray'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ecosse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Ayr'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'ecosse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Galloway'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('mayence', 'MINOR', 'CATHOLIC', '6', '40', '3', '2', '5', null, null, '10', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'mayence'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Mainz'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('mysore', 'ROTW', 'OTHER', null, null, null, null, null, null, null, '9', 'ROTW', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('oldenburg', 'MINOR', 'PROTESTANT', '8', '40', '1', '2', '3', '6', null, '12', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'oldenburg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Münster'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'oldenburg'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Oldenburg'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('azteque', 'ROTW', 'OTHER', null, null, null, null, null, null, null, '16', 'Amerique', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('lucca', 'MINOR', 'CATHOLIC', '8', '40', '2', '3', '1', null, null, '9', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'lucca'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lucca'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('steppes', 'MINOR', 'SUNNITE', '2', '70', '1', '2', '3', '5', '10', '10', 'Islam', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'steppes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Step’'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'steppes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Ural'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'steppes'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bashkiria'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('treves', 'MINOR', 'CATHOLIC', '8', '30', '1', '4', '5', null, null, '14', 'Latin', b'1', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'treves'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Trier'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('sainte-ligue', 'VIRTUAL', 'CATHOLIC', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'sainte-ligue'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Picardie'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'sainte-ligue'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Normandie'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'sainte-ligue'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Maine'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'sainte-ligue'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Provence'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'sainte-ligue'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lyonnais'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'sainte-ligue'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Berry'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'sainte-ligue'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Bourgogne'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'sainte-ligue'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Orléanais'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'sainte-ligue'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Île-de-France'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'sainte-ligue'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Champagne'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('chine', 'ROTW', 'OTHER', null, null, null, null, null, null, null, '10', 'ROTW', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('thuringe', 'MINOR', 'PROTESTANT', '4', '60', '1', '3', '7', null, null, '14', 'Latin', b'0', b'1');
INSERT INTO R_COUNTRY_PROVINCE_EU_CAPITALS (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'thuringe'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Thüringen'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'thuringe'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Franken'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('rebelles', 'VIRTUAL', 'OTHER', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Vfinlande', 'REVOLT', 'PROTESTANT', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vfinlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Finland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vfinlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Tavastland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vfinlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Nyland'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vfinlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Karelen'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vfinlande'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Kexholm'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('Vpommeranie', 'REVOLT', 'PROTESTANT', null, null, null, null, null, null, null, '0', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vpommeranie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Lübeck'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vpommeranie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Holstein'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vpommeranie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Mecklenburg'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vpommeranie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Vorpommern'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vpommeranie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Hinterpommern'));
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'Vpommeranie'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Danzig'));
INSERT INTO R_COUNTRY (NAME, TYPE, RELIGION, RM, SUB, MA, EC, EW, VA, AN, FIDELITY, ARMY_CLASS, ELECTOR, HRE)
    VALUES ('corse', 'REVOLT', 'CATHOLIC', '2', '70', '2', '3', '4', '6', null, '6', 'Latin', b'0', b'0');
INSERT INTO R_COUNTRY_PROVINCE_EU (ID_R_COUNTRY, ID_R_PROVINCE_EU)
    VALUES ( (SELECT ID FROM R_COUNTRY WHERE NAME = 'corse'), (SELECT ID FROM R_PROVINCE WHERE NAME = 'Corsica'));
