CREATE TABLE R_PROVINCE_SEA (
  ID         BIGINT NOT NULL,
  DIFFICULTY INTEGER,
  PENALTY    INTEGER,
  PRIMARY KEY (ID)
);

ALTER TABLE R_PROVINCE_SEA
ADD INDEX FK_R_PROVINCE_SEA_R_PROVINCE (ID),
ADD CONSTRAINT FK_R_PROVINCE_SEA_R_PROVINCE
FOREIGN KEY (ID)
REFERENCES R_PROVINCE (ID);

CREATE TABLE R_PROVINCE_TZ (
  ID         BIGINT NOT NULL,
  TYPE       VARCHAR(255),
  R_PROVINCE VARCHAR(255),
  R_COUNTRY  VARCHAR(255),
  MONOPOLY   INTEGER,
  PRESENCE   INTEGER,
  PRIMARY KEY (ID)
);

ALTER TABLE R_PROVINCE_TZ
ADD INDEX FK_R_PROVINCE_TZ_R_PROVINCE (ID),
ADD CONSTRAINT FK_R_PROVINCE_TZ_R_PROVINCE
FOREIGN KEY (ID)
REFERENCES R_PROVINCE (ID);

CREATE TABLE R_PROVINCE_BOX (
  ID BIGINT NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE R_PROVINCE_BOX
ADD INDEX FK_R_PROVINCE_BOX_R_PROVINCE (ID),
ADD CONSTRAINT FK_R_PROVINCE_BOX_R_PROVINCE
FOREIGN KEY (ID)
REFERENCES R_PROVINCE (ID);

CREATE TABLE R_REGION (
  ID             BIGINT NOT NULL AUTO_INCREMENT,
  NAME           VARCHAR(255),
  INCOME         INTEGER,
  DIFFICULTY     INTEGER,
  TOLERANCE      INTEGER,
  NATIVES_NUMBER INTEGER,
  NATIVES_TYPE   VARCHAR(255),
  COLD_AREA      INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE R_RESOURCES (
  ID          BIGINT NOT NULL AUTO_INCREMENT,
  NUMBER      INTEGER,
  TYPE        VARCHAR(255),
  ID_R_REGION BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE R_RESOURCES
ADD INDEX FK_R_RESOURCES_R_REGION (ID_R_REGION),
ADD CONSTRAINT FK_R_RESOURCES_R_REGION
FOREIGN KEY (ID_R_REGION)
REFERENCES R_REGION (ID);

ALTER TABLE R_PROVINCE_ROTW
ADD COLUMN REGION VARCHAR(255);

ALTER TABLE R_PROVINCE_ROTW
ADD COLUMN FORTRESS INTEGER;

ALTER TABLE R_PROVINCE_ROTW
ADD COLUMN METADATA VARCHAR(255);

