CREATE TABLE T_EXCHEQUER (
  ID     BIGINT NOT NULL AUTO_INCREMENT,
  RESULT VARCHAR(255),
  REGULAR    INTEGER,
  PRESTIGE    INTEGER,
  NATLOAN    INTEGER,
  INTERLOAN    INTEGER,
  PRIMARY KEY (ID)
);

ALTER TABLE ECONOMICAL_SHEET
ADD COLUMN EXCHEQUER_COLUMN INTEGER,
ADD COLUMN EXCHEQUER_BONUS INTEGER,
ADD COLUMN EXCHEQUER_DIE INTEGER;
