ALTER TABLE STACK
ADD COLUMN R_COUNTRY VARCHAR(255);

UPDATE STACK s SET R_COUNTRY = (SELECT R_COUNTRY FROM COUNTER WHERE ID_STACK = s.ID LIMIT 1);

ALTER TABLE STACK
ADD COLUMN MOVE INTEGER NOT NULL DEFAULT 0;