CREATE TABLE T_BATTLE_TECH (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  TECH_FOR VARCHAR(255),
  TECH_AGAINST VARCHAR(255),
  LAND BIT,
  COLUMN_FIRE VARCHAR(255),
  COLUMN_SHOCK VARCHAR(255),
  MORAL INTEGER,
  MORAL_BONUS_VETERAN BIT,
  PRIMARY KEY (ID)
);

