CREATE TABLE DISCOVERY (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  R_PROVINCE  VARCHAR(255),
  TURN INTEGER,
  ID_COUNTRY BIGINT,
  ID_STACK BIGINT,
  PRIMARY KEY (ID)
);

ALTER TABLE DISCOVERY
ADD INDEX FK_DISCOVERY_COUNTRY (ID_COUNTRY),
ADD CONSTRAINT FK_DISCOVERY_COUNTRY
FOREIGN KEY (ID_COUNTRY)
REFERENCES COUNTRY (ID);

ALTER TABLE DISCOVERY
ADD INDEX FK_DISCOVERY_STACK (ID_STACK),
ADD CONSTRAINT FK_DISCOVERY_STACK
FOREIGN KEY (ID_STACK)
REFERENCES STACK (ID);