ALTER TABLE RELATION
DROP FOREIGN KEY FK_RELATION_PLAYER_1;
ALTER TABLE RELATION
DROP INDEX FK_RELATION_PLAYER_1;


ALTER TABLE RELATION
DROP COLUMN ID_PLAYER_FIRST;


ALTER TABLE RELATION
DROP FOREIGN KEY FK_RELATION_PLAYER_2;
ALTER TABLE RELATION
DROP INDEX FK_RELATION_PLAYER_2;


ALTER TABLE RELATION
DROP COLUMN ID_PLAYER_SECOND;

ALTER TABLE RELATION
ADD COLUMN ID_COUNTRY_FIRST BIGINT;

ALTER TABLE RELATION
ADD INDEX FK_RELATION_COUNTRY_1 (ID_COUNTRY_FIRST),
ADD CONSTRAINT FK_RELATION_COUNTRY_1
FOREIGN KEY (ID_COUNTRY_FIRST)
REFERENCES COUNTRY (ID);

ALTER TABLE RELATION
ADD COLUMN ID_COUNTRY_SECOND BIGINT;

ALTER TABLE RELATION
ADD INDEX FK_RELATION_COUNTRY_2 (ID_COUNTRY_SECOND),
ADD CONSTRAINT FK_RELATION_COUNTRY_2
FOREIGN KEY (ID_COUNTRY_SECOND)
REFERENCES COUNTRY (ID);

ALTER TABLE COUNTRY
ADD COLUMN USERNAME VARCHAR(255);


ALTER TABLE PLAYER
DROP FOREIGN KEY FK_PLAYER_GAME;
ALTER TABLE PLAYER
DROP INDEX FK_PLAYER_GAME;

ALTER TABLE PLAYER
DROP FOREIGN KEY FK_PLAYER_COUNTRY;
ALTER TABLE PLAYER
DROP INDEX FK_PLAYER_COUNTRY;

DROP TABLE PLAYER;

CREATE TABLE ECONOMICAL_SHEET (
  ID                   BIGINT NOT NULL AUTO_INCREMENT,
  ID_COUNTRY           BIGINT,
  TURN                 INTEGER,
  RT_START             INTEGER,
  RT_EVENTS            INTEGER,
  LOANS                INTEGER,
  WOOD_SLAVES          INTEGER,
  DIPLO_ACTIONS        INTEGER,
  DIPLO_REACTIONS      INTEGER,
  SUBSIDIES            INTEGER,
  RT_DIPLO             INTEGER,
  PILLAGES             INTEGER,
  GOLD_ROTW            INTEGER,
  EXC_TAXES            INTEGER,
  RT_BEF_EXCH          INTEGER,
  REGULAR_INCOME       INTEGER,
  PRESTIGE_INCOME      INTEGER,
  MAX_NAT_LOAN         INTEGER,
  MAX_INTER_LOAN       INTEGER,
  REMAINING_EXPENSES   INTEGER,
  PRESTIGE_SPENT       INTEGER,
  NAT_LOAN             INTEGER,
  INTER_LOAN           INTEGER,
  RT_BALANCE           INTEGER,
  RT_AFT_EXCH          INTEGER,
  PRESTIGE_VP          INTEGER,
  WEALTH               INTEGER,
  PERIOD_WEALTH        INTEGER,
  STAB                 INTEGER,
  PEACE                INTEGER,
  RT_PEACE             INTEGER,
  INFLATION            INTEGER,
  RT_ENT               INTEGER,
  INTER_LOAN_NEW       INTEGER,
  INTER_LOAN_INTERESTS INTEGER,
  INTER_LOAN_REFUND    INTEGER,
  INTER_BANKRUPT       INTEGER,
  NAT_LOAN_START       INTEGER,
  NAT_LOAN_INTERESTS   INTEGER,
  NAT_LOAN_BANKRUPT    INTEGER,
  NAT_LOAN_REFUND      INTEGER,
  NAT_LOAN_NEW         INTEGER,
  NAT_LOAN_END         INTEGER,
  PROVINCES_INCOME     INTEGER,
  VASSAL_INCOME        INTEGER,
  LOST_INCOME          INTEGER,
  EVENT_LAND_INCOME    INTEGER,
  LAND_INCOME          INTEGER,
  MNU_INCOME           INTEGER,
  GOLD_INCOME          INTEGER,
  INDUSTRIAL_INCOME    INTEGER,
  DOM_TRADE_INCOME     INTEGER,
  FOR_TRADE_INCOME     INTEGER,
  FLEET_LEVEL_INCOME   INTEGER,
  FLEET_MONOP_INCOME   INTEGER,
  TRADE_CENTER_INCOME  INTEGER,
  TRADE_CENTER_LOSS    INTEGER,
  TRADE_INCOME         INTEGER,
  COL_INCOME           INTEGER,
  TP_INCOME            INTEGER,
  EXO_RES_INCOME       INTEGER,
  ROTW_INCOME          INTEGER,
  SPECIAL_INCOME       INTEGER,
  INCOME               INTEGER,
  EVENT_INCOME         INTEGER,
  GROSS_INCOME         INTEGER,
  INTEREST_EXPENSE     INTEGER,
  MAND_REFUND_EXPENSE  INTEGER,
  RT_COLLAPSE          INTEGER,
  OPT_REFUND_EXPENSE   INTEGER,
  UNIT_MAINT_EXPENSE   INTEGER,
  FORT_MAINT_EXPENSE   INTEGER,
  MISS_MAINT_EXPENSE   INTEGER,
  UNIT_PURCH_EXPENSE   INTEGER,
  FORT_PURCH_EXPENSE   INTEGER,
  ADMIN_ACT_EXPENSE    INTEGER,
  ADMIN_REACT_EXPENSE  INTEGER,
  OTHER_EXPENSE        INTEGER,
  ADM_TOTAL_EXPENSE    INTEGER,
  EXC_TAXES_MOD        INTEGER,
  PASS_CAMP_EXPENSE    INTEGER,
  ACT_CAMP_EXPENSE     INTEGER,
  MAJ_CAMP_EXPENSE     INTEGER,
  MULT_CAMP_EXPENSE    INTEGER,
  EXC_RECRUIT_EXPENSE  INTEGER,
  NAVAL_REFIT_EXPENSE  INTEGER,
  PRAESIDIO_EXPENSE    INTEGER,
  MILITARY_EXPENSE     INTEGER,
  EXPENSES             INTEGER,
  PRIMARY KEY (ID)
);

ALTER TABLE ECONOMICAL_SHEET
ADD INDEX FK_ECONOMICAL_SHEET_COUNTRY (ID_COUNTRY),
ADD CONSTRAINT FK_ECONOMICAL_SHEET_COUNTRY
FOREIGN KEY (ID_COUNTRY)
REFERENCES COUNTRY (ID);