ALTER TABLE BATTLE
ADD COLUMN ID_WAR BIGINT NOT NULL,
ADD COLUMN PHASINGOFFENSIVE BIT;

ALTER TABLE BATTLE
ADD INDEX BATTLE_WAR (ID_WAR),
ADD CONSTRAINT BATTLE_WAR
FOREIGN KEY (ID_WAR)
REFERENCES WAR (ID);
