INSERT INTO GAME (ID, STATUS, TURN)
VALUES (1, NULL, NULL);

INSERT INTO COUNTRY (ID, NAME)
VALUES (1, 'FRA');

INSERT INTO STACK (ID, ID_GAME, ID_PROVINCE)
VALUES (1, 1, (SELECT ID
               FROM PROVINCE
               WHERE NAME = 'Prypeć'));

INSERT INTO COUNTER (ID, TYPE, ID_COUNTRY, ID_STACK)
VALUES (1, 'ARMY_PLUS', 1, 1);

INSERT INTO COUNTER (ID, TYPE, ID_COUNTRY, ID_STACK)
VALUES (2, 'ARMY_PLUS', 1, 1);

INSERT INTO STACK (ID, ID_GAME, ID_PROVINCE)
VALUES (2, 1, (SELECT ID
               FROM PROVINCE
               WHERE NAME = 'Prypeć'));

INSERT INTO COUNTER (ID, TYPE, ID_COUNTRY, ID_STACK)
VALUES (3, 'ARMY_PLUS', 1, 2);

INSERT INTO COUNTER (ID, TYPE, ID_COUNTRY, ID_STACK)
VALUES (4, 'ARMY_MINUS', 1, 2);

INSERT INTO STACK (ID, ID_GAME, ID_PROVINCE)
VALUES (3, 1, (SELECT ID
               FROM PROVINCE
               WHERE NAME = 'Prypeć'));

INSERT INTO COUNTER (ID, TYPE, ID_COUNTRY, ID_STACK)
VALUES (5, 'ARMY_PLUS', 1, 3);

INSERT INTO COUNTER (ID, TYPE, ID_COUNTRY, ID_STACK)
VALUES (6, 'ARMY_MINUS', 1, 3);

INSERT INTO COUNTER (ID, TYPE, ID_COUNTRY, ID_STACK)
VALUES (7, 'LAND_DETACHMENT', 1, 3);

INSERT INTO STACK (ID, ID_GAME, ID_PROVINCE)
VALUES (4, 1, (SELECT ID
               FROM PROVINCE
               WHERE NAME = 'Languedoc'));

INSERT INTO COUNTER (ID, TYPE, ID_COUNTRY, ID_STACK)
VALUES (8, 'ARMY_PLUS', 1, 4);

