DROP TABLE T_GOLD;

CREATE TABLE R_GOLD (
  ID         BIGINT NOT NULL AUTO_INCREMENT,
  R_PROVINCE    VARCHAR(255),
  VALUE    INTEGER,
  PRIMARY KEY (ID)
);

ALTER TABLE R_PROVINCE_EU
ADD COLUMN SALT INTEGER;