INSERT INTO GAME (TURN, STATUS, VERSION, SEED)
VALUES (1, 'ADMINISTRATIVE_ACTIONS_CHOICE', 1, 1);

SELECT @idGame := last_insert_id();


INSERT INTO COUNTRY (ID_GAME, NAME, DTI, FTI, FTI_ROTW, READY)
VALUES (@idGame, 'france', 2, 1, 1, b'0');
INSERT INTO ECONOMICAL_SHEET (ID_COUNTRY, TURN, RT_START, RT_EVENTS, RT_DIPLO)
  SELECT
    ID,
    1,
    100,
    100,
    100
  FROM COUNTRY
  WHERE NAME = 'france' AND ID_GAME = @idGame;
INSERT INTO COUNTRY (ID_GAME, NAME, DTI, FTI, FTI_ROTW, READY)
VALUES (@idGame, 'angleterre', 1, 2, 2, b'0');
INSERT INTO ECONOMICAL_SHEET (ID_COUNTRY, TURN, RT_START, RT_EVENTS, RT_DIPLO)
  SELECT
    ID,
    1,
    50,
    50,
    50
  FROM COUNTRY
  WHERE NAME = 'angleterre' AND ID_GAME = @idGame;
INSERT INTO COUNTRY (ID_GAME, NAME, DTI, FTI, FTI_ROTW, READY)
VALUES (@idGame, 'espagne', 1, 2, 2, b'0');
INSERT INTO ECONOMICAL_SHEET (ID_COUNTRY, TURN, RT_START, RT_EVENTS, RT_DIPLO)
  SELECT
    ID,
    1,
    150,
    150,
    150
  FROM COUNTRY
  WHERE NAME = 'espagne' AND ID_GAME = @idGame;
INSERT INTO COUNTRY (ID_GAME, NAME, DTI, FTI, FTI_ROTW, READY)
VALUES (@idGame, 'portugal', 3, 2, 2, b'0');
INSERT INTO ECONOMICAL_SHEET (ID_COUNTRY, TURN, RT_START, RT_EVENTS, RT_DIPLO)
  SELECT
    ID,
    1,
    400,
    400,
    400
  FROM COUNTRY
  WHERE NAME = 'portugal' AND ID_GAME = @idGame;
INSERT INTO COUNTRY (ID_GAME, NAME, DTI, FTI, FTI_ROTW, READY)
VALUES (@idGame, 'turquie', 3, 2, 2, b'0');
INSERT INTO ECONOMICAL_SHEET (ID_COUNTRY, TURN, RT_START, RT_EVENTS, RT_DIPLO)
  SELECT
    ID,
    1,
    400,
    400,
    400
  FROM COUNTRY
  WHERE NAME = 'turquie' AND ID_GAME = @idGame;
INSERT INTO COUNTRY (ID_GAME, NAME, DTI, FTI, FTI_ROTW, READY)
VALUES (@idGame, 'venise', 3, 3, 3, b'0');
INSERT INTO ECONOMICAL_SHEET (ID_COUNTRY, TURN, RT_START, RT_EVENTS, RT_DIPLO)
  SELECT
    ID,
    1,
    200,
    200,
    200
  FROM COUNTRY
  WHERE NAME = 'venise' AND ID_GAME = @idGame;
INSERT INTO COUNTRY (ID_GAME, NAME, DTI, FTI, FTI_ROTW, READY)
VALUES (@idGame, 'pologne', 1, 1, 1, b'0');
INSERT INTO ECONOMICAL_SHEET (ID_COUNTRY, TURN, RT_START, RT_EVENTS, RT_DIPLO)
  SELECT
    ID,
    1,
    100,
    100,
    100
  FROM COUNTRY
  WHERE NAME = 'pologne' AND ID_GAME = @idGame;
INSERT INTO COUNTRY (ID_GAME, NAME, DTI, FTI, FTI_ROTW, READY)
VALUES (@idGame, 'russie', 1, 1, 1, b'0');
INSERT INTO ECONOMICAL_SHEET (ID_COUNTRY, TURN, RT_START, RT_EVENTS, RT_DIPLO)
  SELECT
    ID,
    1,
    100,
    100,
    100
  FROM COUNTRY
  WHERE NAME = 'russie' AND ID_GAME = @idGame;

INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('angleterre', 'ZPangleterre', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('angleterre', 'ZMNord', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('angleterre', 'ZPBaltique', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('angleterre', 'ZMCanarias', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('france', 'ZPfrance', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('france', 'ZMLion', @IdGame, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('france', 'ZMIonienne', @IdGame, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('france', 'ZMCanarias', @IdGame, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('espagne', 'ZPespagne', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('espagne', 'ZMLion', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('espagne', 'ZMCanarias', @IdGame, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('portugal', 'ZMCanarias', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('portugal', 'ZMGuinee', @IdGame, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('turquie', 'ZPturquie', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('turquie', 'ZMNoire W', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('venise', 'ZPvenise', 4, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('venise', 'ZPturquie', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('venise', 'ZMIonienne', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('venise', 'ZMNoire W', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('hollande', 'ZPhollande', 5, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('hollande', 'ZPespagne', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('hollande', 'ZPangleterre', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('hollande', 'ZPfrance', 5, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('hollande', 'ZPBaltique', 4, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('hollande', 'ZMNord', 4, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('hollande', 'ZMLion', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('hollande', 'ZMIonienne', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('ecosse', 'ZMNord', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('danemark', 'ZMNord', @IdGame, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('danemark', 'ZPBaltique', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('hanse', 'ZMNord', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('hanse', 'ZPBaltique', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('suede', 'ZPBaltique', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('genes', 'ZMLion', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('genes', 'ZPespagne', 4, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('genes', 'ZMIonienne', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('oman', 'ZMArabie', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('aden', 'ZMIndien', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('gujarat', 'ZMArabie', 4, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('gujarat', 'ZMIndien', 2, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('gujarat', 'ZMTempetes', @IdGame, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('chine', 'ZMChine', 3, @IdGame);
INSERT INTO TRADE_FLEET (R_COUNTRY, R_PROVINCE, LEVEL, ID_GAME)
VALUES ('japon', 'ZMChine', 3, @IdGame);

-- Neutral
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_21');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_ARQUEBUS', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_40');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_BAROQUE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_34');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_BATTERY', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_28');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_GALLEASS', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_24');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_GALLEON_FLUYT', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_67');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_LACE_WAR', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_51');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_MANOEUVRE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_30');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_MUSKET', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_11');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_NAE_GALEON', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_10');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_RENAISSANCE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_68');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_SEVENTY_FOUR', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_16');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_TERCIO', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_58');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_THREE_DECKER', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_44');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_VESSEL', NULL);

INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PB_0G');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'INFLATION', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PH_0G');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'PA_PRICE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PH_0D');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'SU_PRICE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PH_1G');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FISH_PRICE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PH_1D');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'SALT_PRICE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PH_2G');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'CO_PRICE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PH_2D');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'SL_PRICE', NULL);
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FUR_PRICE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PH_4G');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'SP_PRICE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PH_5D');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'SILK_PRICE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PH_6G');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'PO_PRICE', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_PROD30_1');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FISH_PRODUCTION', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DR_japon');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ROTW_RELATION', 'pologne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ePrypec');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_MINUS', 'japon');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_MR_End');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'GOOD_WEATHER', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_Turn_1');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TURN', NULL);

-- England
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_STAB_1');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'STABILITY', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eUladh');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eConnacht');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eBrega');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eLaighean');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eMumhan');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ePicardie');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FORTRESS_2', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_angleterre-VA');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'ecosse');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eMidlands');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_METAL_MINUS', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eEast Anglia');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_CLOTHES_MINUS', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eWessex');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_FISH_MINUS', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPangleterre');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMNord');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPBaltique');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMCanarias');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_5');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_LAND', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_9');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_NAVAL', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eEast Anglia');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_MINUS', 'angleterre');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'LAND_DETACHMENT', 'angleterre');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eEast Anglia');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FLEET_MINUS', 'angleterre');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'NAVAL_DETACHMENT', 'angleterre');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'NAVAL_TRANSPORT', 'angleterre');


-- France
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_STAB_3');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'STABILITY', 'france');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_france-MA');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'savoie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eChampagne');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_METAL_MINUS', 'france');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eGuyenne');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_WINE_MINUS', 'france');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPfrance');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'france');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMLion');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'france');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMIonienne');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'france');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMCanarias');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'france');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'TECH_LAND',
    'france'
  FROM STACK
  WHERE R_PROVINCE = 'B_TECH_9' AND ID_GAME = @idGame;
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_7');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_NAVAL', 'france');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eIle-de-France');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_PLUS', 'france');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_MINUS', 'france');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'LAND_DETACHMENT', 'france');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eProvence');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'NAVAL_DETACHMENT', 'france');


-- Spain
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_STAB_2');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'STABILITY', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eIlles Balears');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eRosselo');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eSaldigna');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eSicilia');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ePalermo');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eMalta');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eIslas Canarias');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_espagne-SUB');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'genes');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_espagne-RM');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'papaute');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'naples');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eTooledo');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_METAL_MINUS', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPespagne');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMLion');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMCanarias');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'espagne');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'TECH_LAND',
    'espagne'
  FROM STACK
  WHERE R_PROVINCE = 'B_TECH_7' AND ID_GAME = @idGame;
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'TECH_NAVAL',
    'espagne'
  FROM STACK
  WHERE R_PROVINCE = 'B_TECH_9' AND ID_GAME = @idGame;
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eAndalucia');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_PLUS', 'espagne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eAndalucia');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FLEET_MINUS', 'espagne');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'NAVAL_DETACHMENT', 'espagne');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'NAVAL_DETACHMENT', 'espagne');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'NAVAL_DETACHMENT', 'espagne');

-- polonia
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'STABILITY',
    'pologne'
  FROM STACK
  WHERE R_PROVINCE = 'B_STAB_2' AND ID_GAME = @idGame;
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_pologne-VA');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'ukraine');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_pologne-RM');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'hongrie');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'boheme');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eLietuva');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_CEREALS_MINUS', 'pologne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eWielkopolska');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_METAL_MINUS', 'pologne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_6');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_LAND', 'pologne');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_NAVAL', 'pologne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eMalopolska');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_PLUS', 'pologne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eLietuva');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_PLUS', 'pologne');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eUkrainya');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_MINUS', 'ukraine');

-- portugal
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'STABILITY',
    'portugal'
  FROM STACK
  WHERE R_PROVINCE = 'B_STAB_3' AND ID_GAME = @idGame;
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eTanger');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'portugal');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eAcores');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'portugal');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rCabo Verde~I');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'COLONY_PLUS', 'portugal');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rCotedor~W');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'portugal');
# TG-14 mission conception
# INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
# VALUES (@lastId, 'MISSION', 'portugal');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eTejo');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_INSTRUMENTS_MINUS', 'portugal');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eTras-os-Montes');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_WINE_MINUS', 'portugal');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMCanarias');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'portugal');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMGuinee');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'portugal');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'TECH_LAND',
    'portugal'
  FROM STACK
  WHERE R_PROVINCE = 'B_TECH_7' AND ID_GAME = @idGame;
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'TECH_NAVAL',
    'portugal'
  FROM STACK
  WHERE R_PROVINCE = 'B_TECH_10' AND ID_GAME = @idGame;
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eTejo');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_MINUS', 'portugal');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'LAND_DETACHMENT', 'portugal');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eTejo');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FLEET_MINUS', 'portugal');

-- Russia
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'STABILITY',
    'russie'
  FROM STACK
  WHERE R_PROVINCE = 'B_STAB_3' AND ID_GAME = @idGame;
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_russie-MA');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'kazan');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_russie-RM');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'crimee');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eNovgorod');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_CEREALS_MINUS', 'russie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_4');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_LAND', 'russie');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_NAVAL', 'russie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eMoskva');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_PLUS', 'russie');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_PLUS', 'russie');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_PLUS', 'russie');

-- Turkey
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'STABILITY',
    'turquie'
  FROM STACK
  WHERE R_PROVINCE = 'B_STAB_2' AND ID_GAME = @idGame;
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eAlabania');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'turquie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eHellas');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'turquie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eMoreas');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'turquie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eCaffa');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'turquie');
# TG-14 mission conception
# INSERT INTO STACK (ID_GAME, R_PROVINCE)
# VALUES (@IdGame, 'rNedj~W');
# SELECT @lastId := last_insert_id();
# INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
# VALUES (@lastId, 'MISSION', 'turquie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_turquie-VA');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'valachie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_turquie-RM');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'moldavie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eTrakya');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_ART_MINUS', 'turquie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPturquie');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'turquie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMNoire W');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'turquie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_TECH_8');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_LAND', 'turquie');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TECH_NAVAL', 'turquie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eTrakya');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_MINUS', 'turquie');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_TIMAR_PLUS', 'turquie');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_TIMAR_PLUS', 'turquie');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_TIMAR_PLUS', 'turquie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eTrakya');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FLEET_MINUS', 'turquie');
-- TODO TG-5 pashas

-- Venetia
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'STABILITY',
    'venise'
  FROM STACK
  WHERE R_PROVINCE = 'B_STAB_3' AND ID_GAME = @idGame;
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eDalmacija');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eCorfu');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eKreta');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eCyclades');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eChypre');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'B_DE_venise-SUB');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'DIPLOMACY', 'mamelouks');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eVeneto');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADE_CENTER_MEDITERRANEAN', NULL);
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_SALT_PLUS', 'venise');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_ART_MINUS', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eChypre');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'MNU_WINE_MINUS', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPvenise');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_PLUS', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPturquie');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMIonienne');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMNoire W');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'venise');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'TECH_LAND',
    'venise'
  FROM STACK
  WHERE R_PROVINCE = 'B_TECH_5' AND ID_GAME = @idGame;
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
  SELECT
    ID,
    'TECH_NAVAL',
    'venise'
  FROM STACK
  WHERE R_PROVINCE = 'B_TECH_9' AND ID_GAME = @idGame;
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eVeneto');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'ARMY_MINUS', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eVeneto');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FLEET_PLUS', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eMoreas');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FORTRESS_2', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eAlabania');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FORTRESS_2', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eHellas');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FORTRESS_1', 'venise');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eMontenegro');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'FORTRESS_1', 'venise');

-- Minor countries
# TODO TG-149 Tech group
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eTrentino');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'habsbourg');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eBresse');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'savoie');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eGotland');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'danemark');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eVastergotland');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'danemark');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eSkane');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'OWN', 'danemark');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPhollande');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_PLUS', 'hollande');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPespagne');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'hollande');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPangleterre');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'hollande');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPfrance');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_PLUS', 'hollande');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPBaltique');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_PLUS', 'hollande');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMNord');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_PLUS', 'hollande');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMLion');
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'hollande');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMIonienne');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'hollande');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'eVlaanderen');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADE_CENTER_ATLANTIC', NULL);
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMNord');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'ecosse');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMNord');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'danemark');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPBaltique');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'danemark');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMNord');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'hanse');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPBaltique');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'hanse');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPBaltique');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'suede');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMLion');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'genes');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZPespagne');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_PLUS', 'genes');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMIonienne');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'genes');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMOman');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'oman');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMIndien');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'aden');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMOman');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_PLUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMIndien');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMTempetes');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMChine S');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'japon');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'ZMChine S');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_FLEET_MINUS', 'chine');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rOman~E');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'COLONY_PLUS', 'oman');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rNyasa~Z');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'oman');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rAden~E');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'COLONY_PLUS', 'aden');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rGujarat~W');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rMalacca~S');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rMalacca~N');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rNyasa~N');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rKenya~S');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rOrmus~I');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rMumbai~NW');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rMumbai~SW');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rMalabar~N');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rMalabar~S');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'gujarat');
INSERT INTO STACK (ID_GAME, R_PROVINCE)
VALUES (@IdGame, 'rSiberie~S');
SELECT @lastId := last_insert_id();
INSERT INTO COUNTER (ID_STACK, TYPE, R_COUNTRY)
VALUES (@lastId, 'TRADING_POST_MINUS', 'siberie');

-- Colonial sheet and exotic resources

INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Cotedor',
    'TRADING_POST',
    3
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rCotedor~W' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'SL', 3);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Cabo Verde',
    'COLONY',
    4
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'COLONY_PLUS' AND stack.R_PROVINCE = 'rCabo Verde~I' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'FISH', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Oman',
    'COLONY',
    4
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'COLONY_PLUS' AND stack.R_PROVINCE = 'rOman~E' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'SP', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Nyasa',
    'TRADING_POST',
    2
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rNyasa~Z' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'SL', 1);
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'SP', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Aden',
    'COLONY',
    4
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'COLONY_PLUS' AND stack.R_PROVINCE = 'rAden~E' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'SP', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Gujarat',
    'TRADING_POST',
    3
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rGujarat~W' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'SP', 1);
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'PO', 2);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Malacca',
    'TRADING_POST',
    1
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rMalacca~S' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'PO', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Malacca',
    'TRADING_POST',
    1
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rMalacca~N' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'PO', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Nyasa',
    'TRADING_POST',
    1
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rNyasa~N' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'SL', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Kenya',
    'TRADING_POST',
    1
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rKenya~S' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'PO', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Ormus',
    'TRADING_POST',
    1
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rOrmus~I' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'PO', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Mumbai',
    'TRADING_POST',
    2
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rMumbai~NW' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'PO', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Mumbai',
    'TRADING_POST',
    3
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rMumbai~SW' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'PO', 1);
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'SP', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Malabar',
    'TRADING_POST',
    3
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rMalabar~N' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'SP', 2);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Malabar',
    'TRADING_POST',
    2
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rMalabar~S' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'SP', 1);
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'PO', 1);
INSERT INTO ESTABLISHMENT (ID_COUNTER, R_REGION, TYPE, LEVEL)
  SELECT
    counter.ID,
    'Siberie',
    'TRADING_POST',
    3
  FROM COUNTER counter
    INNER JOIN STACK stack ON stack.ID = counter.ID_STACK
  WHERE counter.TYPE = 'TRADING_POST_MINUS' AND stack.R_PROVINCE = 'rSiberie~S' AND stack.ID_GAME = @idGame;
SELECT @lastId := last_insert_id();
INSERT INTO EXOTIC_RESOURCES (ID_ESTABLISHMENT, RESOURCE, NUMBER)
VALUES (@lastId, 'FUR', 2);

-- Chat
INSERT INTO C_ROOM_GLOBAL (ID_GAME)
VALUES (@IdGame);