DELETE FROM T_TRADE;
DELETE FROM T_MNU;
DELETE FROM T_GOLD;
DELETE FROM T_BASIC_FORCE;

INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (1, 1, NULL, 49, 30, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (2, 1, 50, 99, 27, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (3, 1, 100, 149, 24, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (4, 1, 150, 199, 21, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (5, 1, 200, 299, 18, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (6, 1, 300, 399, 15, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (7, 1, 400, 549, 12, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (8, 1, 550, 699, 9, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (9, 1, 700, 899, 6, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (10, 1, 900, 1099, 3, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (11, 1, 1100, NULL, 1, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (12, 2, NULL, 49, 60, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (13, 2, 50, 99, 54, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (14, 2, 100, 149, 48, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (15, 2, 150, 199, 42, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (16, 2, 200, 299, 36, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (17, 2, 300, 399, 30, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (18, 2, 400, 549, 24, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (19, 2, 550, 699, 18, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (20, 2, 700, 899, 12, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (21, 2, 900, 1099, 6, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (22, 2, 1100, NULL, 2, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (23, 3, NULL, 49, 90, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (24, 3, 50, 99, 81, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (25, 3, 100, 149, 72, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (26, 3, 150, 199, 63, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (27, 3, 200, 299, 54, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (28, 3, 300, 399, 45, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (29, 3, 400, 549, 36, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (30, 3, 550, 699, 27, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (31, 3, 700, 899, 18, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (32, 3, 900, 1099, 9, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (33, 3, 1100, NULL, 3, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (34, 4, NULL, 49, 120, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (35, 4, 50, 99, 108, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (36, 4, 100, 149, 96, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (37, 4, 150, 199, 84, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (38, 4, 200, 299, 72, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (39, 4, 300, 399, 60, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (40, 4, 400, 549, 48, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (41, 4, 550, 699, 36, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (42, 4, 700, 899, 24, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (43, 4, 900, 1099, 12, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (44, 4, 1100, NULL, 4, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (45, 5, NULL, 49, 150, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (46, 5, 50, 99, 135, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (47, 5, 100, 149, 120, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (48, 5, 150, 199, 105, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (49, 5, 200, 299, 90, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (50, 5, 300, 399, 75, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (51, 5, 400, 549, 60, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (52, 5, 550, 699, 45, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (53, 5, 700, 899, 30, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (54, 5, 900, 1099, 15, 1);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (55, 5, 1100, NULL, 5, 1);

INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (56, 1, NULL, 40, 1, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (57, 1, 41, 80, 3, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (58, 1, 81, 120, 5, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (59, 1, 121, 160, 7, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (60, 1, 161, 190, 9, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (61, 1, 191, 220, 12, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (62, 1, 221, 240, 15, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (63, 1, 241, 250, 18, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (64, 1, 251, NULL, 20, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (65, 2, NULL, 40, 2, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (66, 2, 41, 80, 6, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (67, 2, 81, 120, 10, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (68, 2, 121, 160, 14, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (69, 2, 161, 190, 18, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (70, 2, 191, 220, 24, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (71, 2, 221, 240, 30, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (72, 2, 241, 250, 36, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (73, 2, 251, NULL, 40, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (74, 3, NULL, 40, 3, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (75, 3, 41, 80, 9, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (76, 3, 81, 120, 15, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (77, 3, 121, 160, 21, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (78, 3, 161, 190, 27, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (79, 3, 191, 220, 36, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (80, 3, 221, 240, 45, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (81, 3, 241, 250, 54, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (82, 3, 251, NULL, 60, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (83, 4, NULL, 40, 4, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (84, 4, 41, 80, 12, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (85, 4, 81, 120, 20, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (86, 4, 121, 160, 28, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (87, 4, 161, 190, 36, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (88, 4, 191, 220, 48, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (89, 4, 221, 240, 60, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (90, 4, 241, 250, 72, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (91, 4, 251, NULL, 80, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (92, 5, NULL, 40, 5, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (93, 5, 41, 80, 15, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (94, 5, 81, 120, 25, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (95, 5, 121, 160, 35, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (96, 5, 161, 190, 45, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (97, 5, 191, 220, 60, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (98, 5, 221, 240, 75, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (99, 5, 241, 250, 90, 0);
INSERT INTO T_TRADE (ID, COUNTRY_VALUE, MIN_VALUE, MAX_VALUE, VALUE, FOREIGN_TRADE)
VALUES (100, 5, 251, NULL, 100, 0);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (1, 'angleterre', 'MNU_ART_MINUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (2, 'angleterre', 'MNU_ART_PLUS', 24);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (3, 'angleterre', 'MNU_WOOD_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (4, 'angleterre', 'MNU_WOOD_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (5, 'angleterre', 'MNU_CEREALS_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (6, 'angleterre', 'MNU_CEREALS_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (7, 'angleterre', 'MNU_INSTRUMENTS_MINUS', 9);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (8, 'angleterre', 'MNU_INSTRUMENTS_PLUS', 18);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (9, 'angleterre', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (10, 'angleterre', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (11, 'angleterre', 'MNU_FISH_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (12, 'angleterre', 'MNU_FISH_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (13, 'angleterre', 'MNU_CLOTHES_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (14, 'angleterre', 'MNU_CLOTHES_PLUS', 12);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (15, 'espagne', 'MNU_ART_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (16, 'espagne', 'MNU_ART_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (17, 'espagne', 'MNU_INSTRUMENTS_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (18, 'espagne', 'MNU_INSTRUMENTS_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (19, 'espagne', 'MNU_METAL_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (20, 'espagne', 'MNU_METAL_PLUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (21, 'espagne', 'MNU_FISH_MINUS', 3);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (22, 'espagne', 'MNU_FISH_PLUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (23, 'espagne', 'MNU_CLOTHES_MINUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (24, 'espagne', 'MNU_CLOTHES_PLUS', 16);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (25, 'espagne', 'MNU_SALT_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (26, 'espagne', 'MNU_SALT_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (27, 'espagne', 'MNU_WINE_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (28, 'espagne', 'MNU_WINE_PLUS', 8);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (29, 'france', 'MNU_ART_MINUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (30, 'france', 'MNU_ART_PLUS', 24);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (31, 'france', 'MNU_WOOD_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (32, 'france', 'MNU_WOOD_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (33, 'france', 'MNU_CEREALS_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (34, 'france', 'MNU_CEREALS_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (35, 'france', 'MNU_INSTRUMENTS_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (36, 'france', 'MNU_INSTRUMENTS_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (37, 'france', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (38, 'france', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (39, 'france', 'MNU_FISH_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (40, 'france', 'MNU_FISH_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (41, 'france', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (42, 'france', 'MNU_CLOTHES_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (43, 'france', 'MNU_SALT_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (44, 'france', 'MNU_SALT_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (45, 'france', 'MNU_WINE_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (46, 'france', 'MNU_WINE_PLUS', 8);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (47, 'habsbourg', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (48, 'habsbourg', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (49, 'habsbourg', 'MNU_CEREALS_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (50, 'habsbourg', 'MNU_CEREALS_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (51, 'habsbourg', 'MNU_INSTRUMENTS_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (52, 'habsbourg', 'MNU_INSTRUMENTS_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (53, 'habsbourg', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (54, 'habsbourg', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (55, 'habsbourg', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (56, 'habsbourg', 'MNU_CLOTHES_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (57, 'habsbourg', 'MNU_SALT_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (58, 'habsbourg', 'MNU_SALT_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (59, 'hollande', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (60, 'hollande', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (61, 'hollande', 'MNU_INSTRUMENTS_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (62, 'hollande', 'MNU_INSTRUMENTS_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (63, 'hollande', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (64, 'hollande', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (65, 'hollande', 'MNU_FISH_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (66, 'hollande', 'MNU_FISH_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (67, 'hollande', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (68, 'hollande', 'MNU_CLOTHES_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (69, 'pologne', 'MNU_ART_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (70, 'pologne', 'MNU_ART_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (71, 'pologne', 'MNU_WOOD_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (72, 'pologne', 'MNU_WOOD_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (73, 'pologne', 'MNU_CEREALS_MINUS', 3);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (74, 'pologne', 'MNU_CEREALS_PLUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (75, 'pologne', 'MNU_INSTRUMENTS_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (76, 'pologne', 'MNU_INSTRUMENTS_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (77, 'pologne', 'MNU_METAL_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (78, 'pologne', 'MNU_METAL_PLUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (79, 'pologne', 'MNU_SALT_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (80, 'pologne', 'MNU_SALT_PLUS', 8);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (81, 'portugal', 'MNU_ART_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (82, 'portugal', 'MNU_ART_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (83, 'portugal', 'MNU_INSTRUMENTS_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (84, 'portugal', 'MNU_INSTRUMENTS_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (85, 'portugal', 'MNU_METAL_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (86, 'portugal', 'MNU_METAL_PLUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (87, 'portugal', 'MNU_FISH_MINUS', 3);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (88, 'portugal', 'MNU_FISH_PLUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (89, 'portugal', 'MNU_SALT_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (90, 'portugal', 'MNU_SALT_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (91, 'portugal', 'MNU_WINE_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (92, 'portugal', 'MNU_WINE_PLUS', 8);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (93, 'prusse', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (94, 'prusse', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (95, 'prusse', 'MNU_WOOD_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (96, 'prusse', 'MNU_WOOD_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (97, 'prusse', 'MNU_INSTRUMENTS_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (98, 'prusse', 'MNU_INSTRUMENTS_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (99, 'prusse', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (100, 'prusse', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (101, 'prusse', 'MNU_METAL_SCHLESIEN_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (102, 'prusse', 'MNU_METAL_SCHLESIEN_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (103, 'prusse', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (104, 'prusse', 'MNU_CLOTHES_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (105, 'russie', 'MNU_ART_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (106, 'russie', 'MNU_ART_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (107, 'russie', 'MNU_WOOD_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (108, 'russie', 'MNU_WOOD_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (109, 'russie', 'MNU_CEREALS_MINUS', 3);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (110, 'russie', 'MNU_CEREALS_PLUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (111, 'russie', 'MNU_INSTRUMENTS_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (112, 'russie', 'MNU_INSTRUMENTS_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (113, 'russie', 'MNU_METAL_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (114, 'russie', 'MNU_METAL_PLUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (115, 'russie', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (116, 'russie', 'MNU_CLOTHES_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (117, 'suede', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (118, 'suede', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (119, 'suede', 'MNU_WOOD_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (120, 'suede', 'MNU_WOOD_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (121, 'suede', 'MNU_INSTRUMENTS_MINUS', 9);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (122, 'suede', 'MNU_INSTRUMENTS_PLUS', 18);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (123, 'suede', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (124, 'suede', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (125, 'suede', 'MNU_FISH_MINUS', 6);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (126, 'suede', 'MNU_FISH_PLUS', 12);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (127, 'suede', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (128, 'suede', 'MNU_CLOTHES_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (129, 'turquie', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (130, 'turquie', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (131, 'turquie', 'MNU_WOOD_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (132, 'turquie', 'MNU_WOOD_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (133, 'turquie', 'MNU_CEREALS_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (134, 'turquie', 'MNU_CEREALS_PLUS', 8);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (135, 'turquie', 'MNU_INSTRUMENTS_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (136, 'turquie', 'MNU_INSTRUMENTS_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (137, 'turquie', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (138, 'turquie', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (139, 'turquie', 'MNU_CLOTHES_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (140, 'turquie', 'MNU_CLOTHES_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (141, 'turquie', 'MNU_SALT_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (142, 'turquie', 'MNU_SALT_PLUS', 10);

INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (143, 'venise', 'MNU_ART_MINUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (144, 'venise', 'MNU_ART_PLUS', 20);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (145, 'venise', 'MNU_INSTRUMENTS_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (146, 'venise', 'MNU_INSTRUMENTS_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (147, 'venise', 'MNU_METAL_MINUS', 7);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (148, 'venise', 'MNU_METAL_PLUS', 14);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (149, 'venise', 'MNU_SALT_MINUS', 5);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (150, 'venise', 'MNU_SALT_PLUS', 10);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (151, 'venise', 'MNU_WINE_MINUS', 4);
INSERT INTO T_MNU (ID, R_COUNTRY, TYPE, VALUE)
VALUES (152, 'venise', 'MNU_WINE_PLUS', 8);

INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (1, 'eToledo', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (2, 'eSalzburg', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (3, 'eKarnten', 50);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (4, 'eBergslagen', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (5, 'eJamtland', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (6, 'eYaroslavl', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (7, 'eUral', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (8, 'eArmenie', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (9, 'rInca~E', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (10, 'rInca~S', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (11, 'rInca~SE', 50);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (12, 'rMinas Gerais~NE', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (13, 'rVenezuela~S', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (14, 'rEcuador~N', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (15, 'rPanama~N', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (16, 'rChichimeca~C', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (17, 'rAzteca~NW', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (18, 'rAzteca~C', 40);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (19, 'rSiberie~NE', 20);
INSERT INTO T_GOLD (ID, R_PROVINCE, VALUE)
VALUES (20, 'rYakoutie~NE', 20);

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (1, 'portugal', 1, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (2, 'portugal', 1, 3, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (3, 'portugal', 2, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (4, 'portugal', 2, 2, 'LDND');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (5, 'suede', 2, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (6, 'suede', 2, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (7, 'suede', 2, 1, 'FLEET_TRANSPORT_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (8, 'suede', 3, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (9, 'suede', 3, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (10, 'suede', 3, 1, 'FLEET_TRANSPORT_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (11, 'suede', 4, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (12, 'suede', 4, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (13, 'suede', 4, 1, 'FLEET_TRANSPORT_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (14, 'suede', 5, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (15, 'suede', 5, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (16, 'suede', 5, 1, 'FLEET_TRANSPORT_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (17, 'suede', 6, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (18, 'suede', 6, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (19, 'suede', 6, 1, 'FLEET_TRANSPORT_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (20, 'suede', 7, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (21, 'suede', 7, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (22, 'suede', 7, 1, 'FLEET_TRANSPORT_PLUS');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (23, 'russie', 1, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (24, 'russie', 2, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (25, 'russie', 3, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (26, 'russie', 3, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (27, 'russie', 3, 2, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (28, 'russie', 4, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (29, 'russie', 4, 1, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (30, 'russie', 5, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (31, 'russie', 5, 2, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (32, 'russie', 6, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (33, 'russie', 6, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (34, 'russie', 6, 2, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (35, 'russie', 6, 3, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (36, 'russie', 6, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (37, 'russie', 6, 3, 'LDND');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (38, 'angleterre', 1, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (39, 'angleterre', 1, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (40, 'angleterre', 2, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (41, 'angleterre', 2, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (42, 'angleterre', 3, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (43, 'angleterre', 3, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (44, 'angleterre', 4, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (45, 'angleterre', 4, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (46, 'angleterre', 5, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (47, 'angleterre', 5, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (48, 'angleterre', 5, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (49, 'angleterre', 6, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (50, 'angleterre', 6, 2, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (51, 'angleterre', 7, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (52, 'angleterre', 7, 2, 'FLEET_PLUS');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (53, 'france', 1, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (54, 'france', 1, 1, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (55, 'france', 2, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (56, 'france', 2, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (57, 'france', 2, 1, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (58, 'france', 3, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (59, 'france', 3, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (60, 'france', 3, 1, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (61, 'france', 4, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (62, 'france', 4, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (63, 'france', 4, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (64, 'france', 5, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (65, 'france', 5, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (66, 'france', 5, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (67, 'france', 6, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (68, 'france', 6, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (69, 'france', 6, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (70, 'france', 7, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (71, 'france', 7, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (72, 'france', 7, 1, 'FLEET_MINUS');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (73, 'espagne', 1, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (74, 'espagne', 1, 3, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (75, 'espagne', 2, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (76, 'espagne', 2, 3, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (77, 'espagne', 3, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (78, 'espagne', 3, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (79, 'espagne', 4, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (80, 'espagne', 4, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (81, 'espagne', 5, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (82, 'espagne', 5, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (83, 'espagne', 6, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (84, 'espagne', 6, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (85, 'espagne', 6, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (86, 'espagne', 7, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (87, 'espagne', 7, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (88, 'espagne', 7, 1, 'LDND');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (89, 'turquie', 1, 3, 'ARMY_TIMAR_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (90, 'turquie', 1, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (91, 'turquie', 1, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (92, 'turquie', 2, 3, 'ARMY_TIMAR_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (93, 'turquie', 2, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (94, 'turquie', 2, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (95, 'turquie', 3, 3, 'ARMY_TIMAR_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (96, 'turquie', 3, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (97, 'turquie', 3, 2, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (98, 'turquie', 4, 3, 'ARMY_TIMAR_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (99, 'turquie', 4, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (100, 'turquie', 4, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (101, 'turquie', 4, 2, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (102, 'turquie', 5, 3, 'ARMY_TIMAR_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (103, 'turquie', 5, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (104, 'turquie', 5, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (105, 'turquie', 6, 3, 'ARMY_TIMAR_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (106, 'turquie', 6, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (107, 'turquie', 6, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (108, 'turquie', 7, 3, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (109, 'turquie', 7, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (110, 'turquie', 7, 1, 'FLEET_PLUS');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (151, 'venise', 1, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (152, 'venise', 1, 3, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (111, 'venise', 2, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (112, 'venise', 2, 3, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (113, 'venise', 3, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (114, 'venise', 3, 3, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (115, 'venise', 4, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (116, 'venise', 4, 2, 'LDND');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (117, 'hollande', 3, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (118, 'hollande', 3, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (119, 'hollande', 3, 1, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (120, 'hollande', 3, 1, 'P_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (121, 'hollande', 4, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (122, 'hollande', 4, 1, 'FLEET_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (123, 'hollande', 4, 1, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (124, 'hollande', 4, 1, 'P_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (125, 'hollande', 5, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (126, 'hollande', 5, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (127, 'hollande', 5, 1, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (128, 'hollande', 5, 1, 'P_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (129, 'hollande', 6, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (130, 'hollande', 6, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (131, 'hollande', 6, 2, 'LDND');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (132, 'hollande', 7, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (133, 'hollande', 7, 1, 'FLEET_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (134, 'hollande', 7, 1, 'LDND');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (135, 'habsbourg', 3, 1, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (136, 'habsbourg', 3, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (137, 'habsbourg', 4, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (138, 'habsbourg', 5, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (139, 'habsbourg', 6, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (140, 'habsbourg', 6, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (141, 'habsbourg', 7, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (142, 'habsbourg', 7, 1, 'ARMY_MINUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (143, 'habsbourg', 7, 1, 'LDND');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (144, 'pologne', 1, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (145, 'pologne', 2, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (146, 'pologne', 3, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (147, 'pologne', 4, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (148, 'pologne', 5, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (149, 'pologne', 6, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (150, 'pologne', 7, 2, 'ARMY_PLUS');

INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (153, 'prusse', 6, 2, 'ARMY_PLUS');
INSERT INTO T_BASIC_FORCE (ID, R_COUNTRY, ID_PERIOD, NUMBER, TYPE)
VALUES (154, 'prusse', 7, 2, 'ARMY_PLUS');