-- Mediterranean sea
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sNoire W');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sNoire E');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sMarmara');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sEgee');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sLevantin');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sAdriatique');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sIonienne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sThyrrenienne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sGabes');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sLion');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sAlboran');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sAlger');

-- Caspian sea
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sCaspienne');

-- Baltic sea
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sOresund');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sBaltique');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sBotnie');

-- Atlantic and North sea
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sNord');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sNorvege');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sRockall');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sIrlande');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sCeltique');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sGascogne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('EUROPE', 'sCadix');
