CREATE TABLE T_LEADER (
  ID     BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  R_COUNTRY VARCHAR(255),
  EVENT VARCHAR(255),
  BEGIN INTEGER,
  END INTEGER,
  RANK VARCHAR(255),
  MANOEUVRE INTEGER,
  FIRE INTEGER,
  SHOCK INTEGER,
  SIEGE INTEGER,
  TYPE VARCHAR(255),
  ROTW   BIT,
  ASIA   BIT,
  AMERICA   BIT,
  PRIVATEER   BIT,
  PRIMARY KEY (ID)
);