ALTER TABLE BATTLE_COUNTER
  ADD COLUMN CODE VARCHAR(255);

UPDATE BATTLE_COUNTER BC
  INNER JOIN COUNTER C ON BC.ID_COUNTER = C.ID
SET BC.CODE = C.CODE;


ALTER TABLE SIEGE_COUNTER
  ADD COLUMN CODE VARCHAR(255);

UPDATE SIEGE_COUNTER SC
  INNER JOIN COUNTER C ON SC.ID_COUNTER = C.ID
SET SC.CODE = C.CODE;