-- Caspian
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE CASPIAN', 'ZMCaspienne');

-- Europe
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZMCaspienne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZMIonienne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZMLion');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZMNoire W');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZMNord');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZPBaltique');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZPangleterre');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZPespagne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZPfrance');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZPhollande');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZPrussie');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZPturquie');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE EUROPE', 'ZPvenise');

-- Mediterranean
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE MEDITERRANEAN', 'ZMCaspienne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE MEDITERRANEAN', 'ZMIonienne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE MEDITERRANEAN', 'ZMLion');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE MEDITERRANEAN', 'ZMNoire W');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE MEDITERRANEAN', 'ZPturquie');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE MEDITERRANEAN', 'ZPvenise');

-- Atlantic
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZMAmerique');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZMCanarias');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZMCaraibes');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZMGuinee');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZMNord');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZMPatagonie');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZMPerou');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZMRecife');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZPangleterre');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZPBaltique');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZPespagne');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZPfrance');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZPhollande');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE ATLANTIC', 'ZPrussie');

-- Indian
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE INDIAN', 'ZMArabie');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE INDIAN', 'ZMChine');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE INDIAN', 'ZMIndien');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE INDIAN', 'ZMTempetes');

-- Trade zone that ... trade
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE TRADE', 'ZMArabie');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE TRADE', 'ZMCanarias');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE TRADE', 'ZMChine');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE TRADE', 'ZMGuinee');
INSERT INTO R_GEO_GROUP (NAME, R_PROVINCE)
VALUES ('TRADE ZONE TRADE', 'ZMIndien');
